from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter()

HTML = r'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI Business OS · Agent에게 맡기기</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f6fa;color:#172033;font-family:Inter,Pretendard,"Noto Sans KR",system-ui,sans-serif}.agent-wrap{max-width:1120px;margin:auto;padding:26px}.muted{color:#65748a;font-size:13px}.top,.stage-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.top h1,.stage h2{margin:4px 0 5px}.badge{display:inline-block;border-radius:999px;padding:5px 9px;background:#edf3ff;color:#1f55b5;font-size:11px;font-weight:800}.tasks{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:18px 0}.task,.step,.btn{border:1px solid #ccd5e2;background:#fff;color:#25344a;border-radius:10px;padding:11px;cursor:pointer;font:inherit;font-weight:700}.task{text-align:left;min-height:90px}.task strong{display:block;margin-bottom:6px}.task.active,.step.active,.btn.primary{background:#2763dc;border-color:#2763dc;color:#fff}.workspace{display:grid;grid-template-columns:205px 1fr;gap:16px}.steps{display:grid;gap:7px;align-content:start}.step{text-align:left}.stage{background:#fff;border:1px solid #dfe5ee;border-radius:14px;padding:20px;min-height:430px}.chat{display:grid;gap:9px;margin:18px 0}.bubble{max-width:86%;border-radius:12px;padding:11px 13px;background:#eef2f7}.bubble.user{justify-self:end;background:#2763dc;color:#fff}.input{width:100%;min-height:88px;border:1px solid #cbd5e1;border-radius:9px;padding:10px;font:inherit}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.plan-row{display:flex;justify-content:space-between;gap:12px;padding:11px 0;border-bottom:1px solid #e5eaf1}.notice{margin:14px 0;padding:12px;border-left:4px solid #2763dc;background:#f2f6ff}.attach{display:block;margin-top:10px}.result{text-align:center;padding:60px 10px}.result-mark{font-size:42px;color:#2e9b69}.mic.listening{background:#b42318;color:#fff}
@media(max-width:760px){.agent-wrap{padding:12px}.tasks{grid-template-columns:repeat(2,1fr)}.workspace{display:block}.steps{grid-template-columns:repeat(5,1fr);margin-bottom:10px}.step{font-size:0;text-align:center}.step span{font-size:13px}.stage{min-height:500px}.top,.stage-head{display:block}}
</style></head><body><main class="agent-wrap"><header class="top"><div><div class="muted">오늘의 업무 › Agent에게 맡기기</div><h1 id="title">신상품 출시 Agent</h1><div class="muted">사람에게 업무를 부탁하듯 말하거나 입력하세요.</div></div><span class="badge">Agent 실행 허용 · ON</span></header>
<section class="tasks"><button class="task active" data-task="new-product"><strong>신상품 출시</strong><span class="muted">등록 준비부터 초안까지</span></button><button class="task" data-task="edit-product"><strong>기존 상품 수정</strong><span class="muted">FACT 확인 후 수정</span></button><button class="task" data-task="sales-channel"><strong>판매채널</strong><span class="muted">채널별 등록 준비</span></button><button class="task" data-task="content"><strong>콘텐츠 제작</strong><span class="muted">이미지·문안·상세페이지</span></button></section>
<section class="workspace"><nav class="steps"><button class="step active" data-step="0"><span>1 요청</span></button><button class="step" data-step="1"><span>2 확인</span></button><button class="step" data-step="2"><span>3 계획</span></button><button class="step" data-step="3"><span>4 승인</span></button><button class="step" data-step="4"><span>5 결과</span></button></nav><div class="stage" id="stage" aria-live="polite"></div></section></main>
<script>(function(){const stage=document.getElementById('stage');let task='new-product',attachmentCount=0;const names={'new-product':'신상품 출시','edit-product':'기존 상품 수정','sales-channel':'판매채널','content':'콘텐츠 제작'},routes={'new-product':'/product-registration','edit-product':'/commerce-catalog','sales-channel':'/commerce-catalog','content':'/products'};
const views=[()=>`<div class="stage-head"><div><h2>무엇을 맡기시겠어요?</h2><p class="muted">음성·텍스트·사진·문서 중 편한 방식으로 요청할 수 있습니다.</p></div><div class="actions"><a class="btn" href="${routes[task]}">직접 입력하기</a><button class="btn mic">🎙 말하기</button></div></div><div class="chat"><div class="bubble">상품명과 원하는 업무를 편하게 말씀해 주세요.</div></div><textarea id="requestText" class="input" placeholder="예: 멀티블루 블루베리 전용비료를 신규 상품으로 등록해줘. 옵션은 없어."></textarea><label class="attach">사진·문서 첨부 <input id="attachments" type="file" multiple></label><div class="actions"><button class="btn primary next">요청 전달</button></div>`,
()=>`<div class="stage-head"><div><h2>필요한 내용만 추가로 확인합니다</h2><p class="muted">기존 FACT와 첨부자료에서 찾지 못한 항목만 질문합니다.</p></div><button class="btn speak">🔊 질문 읽어주기</button></div><div class="chat"><div class="bubble">제조사와 원산지를 확인하지 못했습니다. 두 정보를 알려주시겠어요?</div><div class="bubble user">제조사는 멀티블루이고 원산지는 대한민국이야.</div><div class="bubble">‘제조사: 멀티블루, 원산지: 대한민국’으로 이해했습니다.</div></div><textarea class="input" placeholder="말하거나 입력해 주세요."></textarea><div class="actions"><button class="btn mic">🎙 말로 답하기</button><button class="btn primary next">맞아요, 계속</button></div>`,
()=>`<div class="stage-head"><div><h2>실행계획을 확인해 주세요</h2><p class="muted">계획을 음성으로 듣거나 수정 요청할 수 있습니다.</p></div><button class="btn speak">🔊 계획 읽어주기</button></div><div class="plan-row"><span>상품 초안</span><strong>1개 생성</strong></div><div class="plan-row"><span>상품코드</span><strong>공통 기능으로 자동 발급</strong></div><div class="plan-row"><span>SKU</span><strong>단일 SKU 생성</strong></div><div class="plan-row"><span>첨부자료</span><strong>${attachmentCount}개 연결</strong></div><div class="plan-row"><span>외부 판매채널</span><strong>등록하지 않음</strong></div><div class="plan-row"><span>예상 비용</span><strong>실행 전 확정 범위 내</strong></div><div class="actions"><button class="btn mic">🎙 음성으로 수정</button><button class="btn primary next">이 계획으로 계속</button></div>`,
()=>`<div class="stage-head"><div><h2>최종 실행 승인</h2><p class="muted">음성 승인은 의사 표현으로만 기록되며 버튼을 눌러야 확정됩니다.</p></div><span class="badge">중요 작업 보호</span></div><div class="notice"><strong>이번 승인 범위</strong><p>내부 상품 초안과 SKU를 생성하고 자료를 연결합니다. 외부 게시·가격 변경·판매 시작은 하지 않습니다.</p></div><label><input id="confirm" type="checkbox"> 위 실행 범위와 변경사항을 확인했습니다.</label><div class="actions"><button class="btn" id="backPlan">계획으로 돌아가기</button><button class="btn primary" id="approve" disabled>Agent 실행 승인</button></div>`,
()=>`<div class="result"><div class="result-mark">✓</div><h2>승인 흐름 확인 완료</h2><p>배포 전 UI 구현본이며 외부 판매채널 작업은 실행하지 않았습니다.</p><div class="actions" style="justify-content:center"><button class="btn speak">🔊 결과 읽어주기</button><a class="btn" href="/commerce-catalog">통합상품관리에서 확인</a><button class="btn primary" id="restart">다음 업무 요청</button></div></div>`];
function setStep(n){stage.innerHTML=views[n]();document.querySelectorAll('.step').forEach((b,i)=>b.classList.toggle('active',i===n));stage.querySelectorAll('.next').forEach(b=>b.onclick=()=>setStep(n+1));const f=stage.querySelector('#attachments');if(f)f.onchange=()=>attachmentCount=f.files.length;stage.querySelectorAll('.mic').forEach(b=>b.onclick=()=>listen(b,stage.querySelector('textarea')));stage.querySelectorAll('.speak').forEach(b=>b.onclick=()=>speak(stage.innerText));const c=stage.querySelector('#confirm'),a=stage.querySelector('#approve');if(c&&a){c.onchange=()=>a.disabled=!c.checked;a.onclick=()=>setStep(4)}const back=stage.querySelector('#backPlan');if(back)back.onclick=()=>setStep(2);const restart=stage.querySelector('#restart');if(restart)restart.onclick=()=>setStep(0)}
function listen(button,target){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){target&&target.focus();alert('이 브라우저는 음성 받아쓰기를 지원하지 않습니다. 텍스트로 입력해 주세요.');return}const r=new SR();r.lang='ko-KR';button.classList.add('listening');button.textContent='듣는 중…';r.onresult=e=>{if(target)target.value=(target.value+' '+e.results[0][0].transcript).trim()};r.onend=()=>{button.classList.remove('listening');button.textContent='🎙 말하기'};r.start()}function speak(text){if(!('speechSynthesis'in window)){alert('이 브라우저는 음성 읽기를 지원하지 않습니다.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ko-KR';speechSynthesis.speak(u)}
document.querySelectorAll('.step').forEach(b=>b.onclick=()=>setStep(Number(b.dataset.step)));document.querySelectorAll('.task').forEach(b=>b.onclick=()=>{task=b.dataset.task;document.querySelectorAll('.task').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('title').textContent=names[task]+' Agent';setStep(0)});const q=new URLSearchParams(location.search).get('task');if(names[q])document.querySelector(`.task[data-task="${q}"]`).click();else setStep(0)})();</script></body></html>'''


@router.get("/agent-workspace", response_class=HTMLResponse, include_in_schema=False)
def agent_workspace():
    return HTMLResponse(HTML, headers={"Cache-Control": "no-store"})
