from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter()

HTML = r'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI Business OS · Agent에게 맡기기</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f6fa;color:#172033;font-family:Inter,Pretendard,"Noto Sans KR",system-ui,sans-serif}.agent-wrap{max-width:1120px;margin:auto;padding:26px}.muted{color:#65748a;font-size:13px}.top,.stage-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.top h1,.stage h2{margin:4px 0 5px}.badge{display:inline-block;border-radius:999px;padding:5px 9px;background:#edf3ff;color:#1f55b5;font-size:11px;font-weight:800}.tasks{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:18px 0}.task,.step,.btn{border:1px solid #ccd5e2;background:#fff;color:#25344a;border-radius:10px;padding:11px;cursor:pointer;font:inherit;font-weight:700}.task{text-align:left;min-height:90px}.task strong{display:block;margin-bottom:6px}.task.active,.step.active,.btn.primary{background:#2763dc;border-color:#2763dc;color:#fff}.workspace{display:grid;grid-template-columns:205px 1fr;gap:16px}.steps{display:grid;gap:7px;align-content:start}.step{text-align:left}.stage{background:#fff;border:1px solid #dfe5ee;border-radius:14px;padding:20px;min-height:430px}.chat{display:grid;gap:9px;margin:18px 0}.bubble{max-width:86%;border-radius:12px;padding:11px 13px;background:#eef2f7}.bubble.user{justify-self:end;background:#2763dc;color:#fff}.input{width:100%;min-height:88px;border:1px solid #cbd5e1;border-radius:9px;padding:10px;font:inherit}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.plan-row{display:flex;justify-content:space-between;gap:12px;padding:11px 0;border-bottom:1px solid #e5eaf1}.notice{margin:14px 0;padding:12px;border-left:4px solid #2763dc;background:#f2f6ff}.attach{display:block;margin-top:10px}.result{text-align:center;padding:60px 10px}.result-mark{font-size:42px;color:#2e9b69}.mic.listening{background:#b42318;color:#fff}.generic-agent .tasks{display:none}.generic-agent .agent-wrap{max-width:980px}.generic-agent .workspace{margin-top:20px}
@media(max-width:760px){.agent-wrap{padding:12px}.tasks{grid-template-columns:repeat(2,1fr)}.workspace{display:block}.steps{grid-template-columns:repeat(5,1fr);margin-bottom:10px}.step{font-size:0;text-align:center}.step span{font-size:13px}.stage{min-height:500px}.top,.stage-head{display:block}}
</style></head><body><main class="agent-wrap"><header class="top"><div><div class="muted" id="agentBreadcrumb">오늘의 업무 › Agent에게 맡기기</div><h1 id="title">신상품 출시 Agent</h1><div class="muted" id="agentSubtitle">사람에게 업무를 부탁하듯 말하거나 입력하세요.</div></div><span class="badge">Agent 실행 허용 · ON</span></header>
<section class="tasks"><button class="task active" data-task="new-product"><strong>신상품 출시</strong><span class="muted">등록 준비부터 초안까지</span></button><button class="task" data-task="edit-product"><strong>기존 상품 수정</strong><span class="muted">FACT 확인 후 수정</span></button><button class="task" data-task="sales-channel"><strong>판매채널</strong><span class="muted">채널별 등록 준비</span></button><button class="task" data-task="content"><strong>콘텐츠 제작</strong><span class="muted">이미지·문안·상세페이지</span></button></section>
<section class="workspace"><nav class="steps"><button class="step active" data-step="0"><span>1 요청</span></button><button class="step" data-step="1"><span>2 확인</span></button><button class="step" data-step="2"><span>3 계획</span></button><button class="step" data-step="3"><span>4 승인</span></button><button class="step" data-step="4"><span>5 결과</span></button></nav><div class="stage" id="stage" aria-live="polite"></div></section></main>
<script>(function(){const stage=document.getElementById('stage'),query=new URLSearchParams(location.search),genericMode=location.pathname==='/agent-request';let task=genericMode?'general':'new-product',attachments=[],requestText=query.get('request')||'',answerText='',confirmationMessages=[],confirmationReady=false,voiceConversation=false,planRevision='',currentStep=0,maxStep=0,runData=null,toolPlan=null,selectedProductId='',toolArgs={},contextProductId=query.get('context_product_id')||'',sourcePath=query.get('source_path')||'';const names={'general':'일반 요청','new-product':'신상품 출시','edit-product':'기존 상품 수정','sales-channel':'판매채널','content':'콘텐츠 제작'};
const views=[()=>`<div class="stage-head"><div><h2>${genericMode?'무엇을 도와드릴까요?':'무엇을 맡기시겠어요?'}</h2><p class="muted">${genericMode?'업무 종류를 고르지 말고 필요한 내용을 자유롭게 말씀해 주세요.':'음성·텍스트·사진·문서 중 편한 방식으로 요청할 수 있습니다.'}</p></div><button class="btn mic">🎙 말하기</button></div>${sourcePath?`<div class="notice"><strong>현재 업무 화면에서 호출됨</strong><p>${esc(sourcePath)}${contextProductId?' · 현재 상품이 자동 연결됩니다.':''}</p></div>`:''}<textarea id="requestText" class="input" placeholder="${genericMode?'예: 이 상품 배송비 알려줘, 5kg SKU 추가해줘':'상품명과 원하는 업무를 입력해 주세요.'}">${esc(requestText)}</textarea><label class="attach btn">＋ 사진·문서 첨부<input id="attachments" type="file" multiple hidden></label><div id="fileList">${fileList()}</div><div class="actions"><button class="btn primary next">요청 전달</button></div>`,
()=>`<div class="stage-head"><div><h2>요청 내용을 확인해 주세요</h2><p class="muted">Agent와 필요한 내용을 확인한 뒤 계획 단계로 이동합니다.</p></div><button class="btn${voiceConversation?' primary':''}" id="voiceConversation">🔊 음성 대화 ${voiceConversation?'켜짐':'켜기'}</button></div><div class="chat"><div class="bubble">요청: ${esc(requestText)}</div><div class="bubble">${esc(toolPlan&&toolPlan.tool_label||'등록되지 않은 요청')}</div>${targetChoices()}<div class="bubble">빠진 내용이나 반드시 지켜야 할 조건이 있으면 알려주세요. 없으면 ‘추가사항 없음’이라고 답해 주세요.</div>${confirmationMessages.map(m=>`<div class="bubble${m.role==='user'?' user':''}">${esc(m.text)}</div>`).join('')}</div><textarea id="answerText" class="input" placeholder="Agent에게 답변하거나 추가 조건을 입력해 주세요.">${esc(answerText)}</textarea><div class="actions">${voiceConversation?'':'<button class="btn mic">🎙 말하기</button>'}<button class="btn primary" id="sendAnswer">답변 전달</button>${confirmationReady?'<button class="btn next">확인하고 계속</button>':''}</div><p id="answerError" class="muted" role="alert"></p>`,
()=>`<div class="stage-head"><div><h2>실행계획을 확인해 주세요</h2><p class="muted">실행할 도구·대상·값을 확인합니다.</p></div><button class="btn${voiceConversation?' primary':''}" id="voiceConversation">🔊 음성 대화 ${voiceConversation?'켜짐':'켜기'}</button></div>${planSummary()}${skuInputs()}<textarea id="planRevision" class="input" placeholder="수정하거나 추가할 내용을 입력해 주세요.">${esc(planRevision)}</textarea><div class="actions">${voiceConversation?'':'<button class="btn mic">🎙 말하기</button>'}<button class="btn" id="revisePlan">계획 수정 요청</button><button class="btn primary next">이 계획으로 계속</button></div>`,
()=>`<div class="stage-head"><div><h2>${toolPlan.approval_required?'최종 실행 승인':'조회 실행 확인'}</h2><p class="muted">${toolPlan.approval_required?'버튼을 눌러야 내부 데이터가 변경됩니다.':'조회 전용이며 상품 데이터는 변경하지 않습니다.'}</p></div><span class="badge">${esc(toolPlan.risk)}</span></div><div class="notice"><strong>${esc(toolPlan.tool_label)}</strong><p>외부 게시·가격 변경·판매 시작은 하지 않습니다.</p></div>${toolPlan.approval_required?'<label><input id="confirm" type="checkbox"> 위 실행 범위와 변경사항을 확인했습니다.</label>':''}<div class="actions"><button class="btn" id="backPlan">계획으로 돌아가기</button><button class="btn primary" id="approve" ${toolPlan.approval_required?'disabled':''}>${toolPlan.approval_required?'Agent 실행 승인':'조회 실행'}</button></div>`,
()=>`<div class="result"><div class="result-mark">${runData&&runData.status==='failed'?'!':'✓'}</div>${resultMarkup()}<div class="actions" style="justify-content:center"><button class="btn speak">🔊 결과 읽어주기</button><a class="btn" href="/dashboard">실행 기록 확인</a><a class="btn" href="/commerce-catalog">통합상품관리에서 확인</a><button class="btn primary" id="restart">다음 업무 요청</button></div></div>`];
function esc(v){return String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function targetChoices(){if(!toolPlan)return '';if(toolPlan.action==='category_products')return `<div class="notice">카테고리: ${esc(toolPlan.category_query)}</div>`;if(!toolPlan.candidates.length)return '<div class="notice">비슷한 상품을 찾지 못했습니다. 상품명이나 상품코드를 더 정확히 입력해 주세요.</div>';return toolPlan.candidates.map(p=>`<label class="bubble" style="display:block"><input type="radio" name="productTarget" value="${esc(p.id)}" ${selectedProductId===p.id?'checked':''}> ${esc(p.name)} · ${esc(p.product_code)} · ${esc(p.category||'카테고리 없음')}</label>`).join('')}
function selectedProduct(){return toolPlan&&toolPlan.candidates.find(p=>p.id===selectedProductId)}
function planSummary(){const rows=[['도구',toolPlan.tool_label],['위험 등급',toolPlan.risk==='read'?'조회 전용':'내부 데이터 변경'],['대상',selectedProduct()?.name||toolPlan.category_query||'-'],['첨부자료',(toolPlan.staged_attachments||[]).length+'개'],['외부 판매채널','실행하지 않음']];return rows.map(r=>`<div class="plan-row"><span>${r[0]}</span><strong>${esc(r[1])}</strong></div>`).join('')}
function skuInputs(){if(!toolPlan||toolPlan.action!=='sku_add')return '';return `<div class="plan-row"><span>SKU명 *</span><input data-arg="name" value="${esc(toolArgs.name||'')}"></div><div class="plan-row"><span>옵션값</span><input data-arg="option_value" value="${esc(toolArgs.option_value||'')}"></div><div class="plan-row"><span>판매가 *</span><input type="number" data-arg="sale_price" value="${esc(toolArgs.sale_price??'')}"></div><div class="plan-row"><span>배송비</span><input type="number" data-arg="shipping_fee" value="${esc(toolArgs.shipping_fee??'')}"></div><div class="plan-row"><span>초기 재고</span><input type="number" data-arg="current_stock" value="${esc(toolArgs.current_stock??0)}"></div>`}
function resultMarkup(){if(!runData)return '<h2>실행 결과를 확인하고 있습니다.</h2>';if(runData.status==='failed')return `<h2>실행 실패</h2><p>${esc(runData.result)}</p>`;let d=null;try{d=JSON.parse(runData.result)}catch(e){}if(!d)return '<h2>실행 결과를 확인하고 있습니다.</h2>';const title=d.verified?(d.actual_change?'실제 변경 완료':'조회 완료'):'요청 기록 완료 · 실제 상품 변경 없음';let body='';if(d.skus)body+=d.skus.map(s=>`<div class="bubble">${esc(s.sku_code)} · ${esc(s.name)} · 판매가 ${s.sale_price??'-'}원 · 배송비 ${s.shipping_fee??'-'}원 · 재고 ${s.available_stock??'-'}</div>`).join('');if(d.products)body+=d.products.map(p=>`<div class="bubble"><a href="${esc(p.management_url)}">${esc(p.name)}</a> · ${esc(p.product_code)}</div>`).join('');if(d.images)body+=d.images.map(i=>`<div class="bubble"><img src="${esc(i.content_url)}" style="max-width:180px"><br>${esc(i.filename)}</div>`).join('');if(d.detail_page)body+=`<p><a class="btn" href="${esc(d.detail_page.url)}">상세페이지 열기</a></p>`;if(d.internal_records)body+=`<p>네이버 내부 연결 기록 ${d.internal_records.length}건</p><p class="muted">${esc(d.notice)}</p>`;if(d.sku)body+=`<div class="notice">${esc(d.sku.sku_code)} · ${esc(d.sku.name)} · ${d.sku.sale_price}원</div>`;return `<h2>${title}</h2>${body}<p>${esc(d.message||'저장 후 재조회 검증을 완료했습니다.')}</p>`}
function confirmedAnswers(){return confirmationMessages.filter(m=>m.role==='user').map(m=>m.text).join(' / ')}
function fileKey(f){return `${f.name}:${f.size}:${f.lastModified}`}
function fileList(){return attachments.map((f,i)=>`<div class="bubble">${esc(f.name)} · ${Math.ceil(f.size/1024)}KB <button class="btn" onclick="removeFile(${i})">삭제</button></div>`).join('')||'<p class="muted">첨부된 파일 없음</p>'}
function removeFile(i){attachments.splice(i,1);const box=document.getElementById('fileList');if(box)box.innerHTML=fileList()}
function addFiles(files){const keys=new Set(attachments.map(fileKey));for(const f of files){if(!keys.has(fileKey(f))){attachments.push(f);keys.add(fileKey(f))}}const box=document.getElementById('fileList');if(box)box.innerHTML=fileList()}
function remember(){const r=document.getElementById('requestText'),a=document.getElementById('answerText'),p=document.getElementById('planRevision');if(r)requestText=r.value.trim();if(a)answerText=a.value.trim();if(p)planRevision=p.value.trim();document.querySelectorAll('[data-arg]').forEach(el=>toolArgs[el.dataset.arg]=el.type==='number'?(el.value===''?null:Number(el.value)):el.value.trim())}
async function api(path,options={}){const r=await fetch(path,{credentials:'same-origin',...options}),d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:JSON.stringify(d.detail||r.status));return d}
async function preparePlan(){remember();if(!requestText){alert('요청 내용을 입력해 주세요.');return}const form=new FormData();form.append('request_text',requestText);form.append('workflow',names[task]);if(contextProductId)form.append('context_product_id',contextProductId);attachments.forEach(f=>form.append('files',f));try{toolPlan=await api('/api/v1/agent-tools/plan',{method:'POST',body:form});if(!toolPlan.supported){alert(toolPlan.message+'\n지원 도구: '+toolPlan.available_tools.join(', '));return}toolArgs={...(toolPlan.args||{})};const contextCandidate=toolPlan.candidates.find(x=>x.id===contextProductId);selectedProductId=contextCandidate?contextCandidate.id:(toolPlan.candidates.length===1?toolPlan.candidates[0].id:'');maxStep=1;setStep(1)}catch(e){alert(String(e))}}
async function executeAgent(){remember();maxStep=4;const body={action:toolPlan.action,product_id:selectedProductId||null,category_query:toolPlan.category_query||null,staged_attachment_ids:(toolPlan.staged_attachments||[]).map(x=>x.stage_id),args:toolArgs,approval_confirmed:!!toolPlan.approval_required,tenant_id:'__legacy__',agent_id:'__legacy_default_agent__'};try{runData=await api('/api/v1/agent-tools/execute',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setStep(4);for(let i=0;i<40&&['queued','running'].includes(runData.status);i++){await new Promise(r=>setTimeout(r,1000));runData=await api('/api/v1/runs/'+runData.id);setStep(4)}}catch(e){runData={status:'failed',result:String(e)};setStep(4)}}
function latestAgentSpeech(){const last=[...confirmationMessages].reverse().find(m=>m.role==='agent');return last?last.text:'빠진 내용이나 반드시 지켜야 할 조건이 있으면 알려주세요. 없으면 추가사항 없음이라고 답해 주세요.'}
function continueVoiceConversation(){if(!voiceConversation)return;if(currentStep===1)speak(latestAgentSpeech(),()=>listen(null,stage.querySelector('#answerText')));if(currentStep===2)speak(`업무 ${names[task]}. 요청 ${requestText}. 추가 조건 ${confirmedAnswers()||'없음'}. 첨부자료 ${attachments.length}개. 외부 판매채널은 실행하지 않습니다. 수정할 내용이 있으면 말씀해 주세요.`,()=>listen(null,stage.querySelector('#planRevision')))}
function toggleVoiceConversation(){voiceConversation=!voiceConversation;setStep(currentStep);if(voiceConversation)continueVoiceConversation();else if('speechSynthesis'in window)speechSynthesis.cancel()}
function sendConfirmationAnswer(){remember();const error=stage.querySelector('#answerError'),field=stage.querySelector('#answerText');if(!answerText){if(error)error.textContent='답변을 입력한 뒤 전달해 주세요.';field?.focus();return}confirmationMessages.push({role:'user',text:answerText});const summary=/^(없음|없어요|추가사항 없음|그대로|맞아|맞아요)[.! ]*$/.test(answerText)?'추가 조건은 없는 것으로 이해했습니다. 이 내용으로 실행계획을 만들까요?':`추가 조건을 “${answerText}”로 이해했습니다. 더 확인할 내용이 있으면 입력하고, 맞으면 확인하고 계속을 눌러 주세요.`;confirmationMessages.push({role:'agent',text:summary});confirmationReady=true;if(field)field.value='';answerText='';setStep(1);continueVoiceConversation()}
function setStep(n){if(n>maxStep)return;remember();currentStep=n;stage.innerHTML=views[n]();document.querySelectorAll('.step').forEach((b,i)=>{b.classList.toggle('active',i===n);b.disabled=i>maxStep});stage.querySelectorAll('.next').forEach(b=>b.onclick=()=>{remember();if(n===0)return preparePlan();if(n===1){const checked=stage.querySelector('input[name="productTarget"]:checked');if(checked)selectedProductId=checked.value;if(toolPlan.action!=='category_products'&&!selectedProductId){alert('대상 상품을 먼저 선택해 주세요.');return}}if(n===2&&toolPlan.action==='sku_add'&&(!toolArgs.name||toolArgs.sale_price===null)){alert('SKU명과 판매가는 필수입니다.');return}maxStep=Math.max(maxStep,n+1);setStep(n+1);if(voiceConversation&&currentStep===2)continueVoiceConversation()});const f=stage.querySelector('#attachments');if(f)f.onchange=()=>{addFiles(f.files);f.value=''};stage.querySelectorAll('.mic').forEach(b=>b.onclick=()=>listen(b,stage.querySelector('textarea')));stage.querySelectorAll('.speak').forEach(b=>b.onclick=()=>speak(stage.innerText));const voice=stage.querySelector('#voiceConversation');if(voice)voice.onclick=toggleVoiceConversation;const send=stage.querySelector('#sendAnswer');if(send)send.onclick=sendConfirmationAnswer;const revise=stage.querySelector('#revisePlan');if(revise)revise.onclick=()=>{remember();alert('수정 요청을 계획에 반영했습니다.');setStep(2);continueVoiceConversation()};const c=stage.querySelector('#confirm'),a=stage.querySelector('#approve');if(a){if(c)c.onchange=()=>a.disabled=!c.checked;a.onclick=executeAgent}const back=stage.querySelector('#backPlan');if(back)back.onclick=()=>setStep(2);const restart=stage.querySelector('#restart');if(restart)restart.onclick=()=>{attachments=[];requestText='';answerText='';confirmationMessages=[];confirmationReady=false;planRevision='';runData=null;toolPlan=null;selectedProductId='';toolArgs={};maxStep=0;setStep(0)}}
function listen(button,target){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){target&&target.focus();voiceConversation=false;alert('이 브라우저는 음성 받아쓰기를 지원하지 않습니다. 텍스트로 입력해 주세요.');return}const r=new SR();r.lang='ko-KR';if(button){button.classList.add('listening');button.textContent='듣는 중…'}r.onresult=e=>{if(target)target.value=(target.value+' '+e.results[0][0].transcript).trim()};r.onend=()=>{if(button){button.classList.remove('listening');button.textContent='🎙 말하기'}};r.onerror=()=>{target&&target.focus()};try{r.start()}catch(e){target&&target.focus()}}function speak(text,onend){if(!('speechSynthesis'in window)){voiceConversation=false;alert('이 브라우저는 음성 읽기를 지원하지 않습니다. 텍스트로 확인해 주세요.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ko-KR';if(onend)u.onend=onend;speechSynthesis.speak(u)}
document.querySelectorAll('.step').forEach(b=>b.onclick=()=>setStep(Number(b.dataset.step)));document.querySelectorAll('.task').forEach(b=>b.onclick=()=>{task=b.dataset.task;attachments=[];requestText='';answerText='';confirmationMessages=[];confirmationReady=false;planRevision='';runData=null;maxStep=0;document.querySelectorAll('.task').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('title').textContent=names[task]+' Agent';setStep(0)});if(genericMode){document.body.classList.add('generic-agent');document.getElementById('agentBreadcrumb').textContent='현재 업무 › Agent에게 요청';document.getElementById('title').textContent='AI Business OS Agent';document.getElementById('agentSubtitle').textContent='필요한 업무를 말하면 실행 가능한 도구와 승인 범위를 먼저 확인합니다.';setStep(0)}else{const q=query.get('task');if(names[q])document.querySelector(`.task[data-task="${q}"]`).click();else setStep(0)}})();</script></body></html>'''


@router.get("/agent-workspace", response_class=HTMLResponse, include_in_schema=False)
def agent_workspace():
    return HTMLResponse(HTML, headers={"Cache-Control": "no-store"})


@router.get("/agent-request", response_class=HTMLResponse, include_in_schema=False)
def agent_request():
    return HTMLResponse(HTML, headers={"Cache-Control": "no-store"})
