from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter()

HTML = r'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>통합 상품관리</title><style>
*{box-sizing:border-box}body{margin:0;background:#0b0f17;color:#e5e7eb;font-family:Inter,Pretendard,system-ui,sans-serif}.wrap{max-width:1450px;margin:auto;padding:28px}a{color:#bfdbfe;text-decoration:none}.top,.tabs,.toolbar{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.top{justify-content:space-between;margin-bottom:18px}.tabs{margin:14px 0}.tabs button,.toolbar button{border:1px solid #35445a;background:#182337;color:white;border-radius:9px;padding:9px 13px}.tabs button.on{background:#e5e7eb;color:#111827}.card{background:#111827;border:1px solid #263247;border-radius:15px;overflow:hidden}.toolbar{padding:14px;border-bottom:1px solid #263247}.toolbar input,.toolbar select{background:#0b1220;color:#fff;border:1px solid #35445a;border-radius:9px;padding:10px}.toolbar input{min-width:320px;flex:1}.table{overflow:auto}table{border-collapse:collapse;width:100%;min-width:1240px}th,td{border-bottom:1px solid #253044;padding:12px;text-align:left;font-size:13px}th{color:#8ea0b7;background:#0d1421;cursor:pointer}.code{font-family:ui-monospace,monospace;color:#bfdbfe}.muted{color:#8ea0b7}.pill{border:1px solid #35445a;border-radius:999px;padding:3px 7px;font-size:11px}.ok{color:#a7f3d0}.danger{border:1px solid #7f1d1d;background:#3f1519;color:#fecaca;border-radius:8px;padding:6px 10px;cursor:pointer}.danger:hover{background:#7f1d1d}.empty{padding:35px;text-align:center;color:#8ea0b7}.summary{margin:8px 0 16px;color:#8ea0b7}@media(max-width:700px){.wrap{padding:16px}.toolbar input{min-width:100%}}
</style></head><body><div class="wrap"><div class="top"><div><h1 style="margin:0">통합 상품관리</h1><div class="muted">AI Business OS의 원본 장부 · 쇼핑몰 연결 기준</div></div><div><a href="/dashboard">대시보드</a> · <a href="/product-registration">＋ 상품 등록</a></div></div><div class="summary" id="summary">불러오는 중…</div><div class="tabs"><button id="productTab" class="on" onclick="setTab('product')">상품 목록</button><button id="skuTab" onclick="setTab('sku')">SKU 목록</button></div><div class="card"><div class="toolbar"><input id="q" placeholder="상품코드 · SKU · 상품명 · 옵션 · 바코드 통합검색" oninput="render()"><select id="status" onchange="render()"><option value="">전체 상태</option><option value="draft">초안</option><option value="active">활성</option><option value="inactive">비활성</option></select><select id="channel" onchange="render()"><option value="">전체 채널</option><option value="naver">네이버</option><option value="coupang">쿠팡</option><option value="own_store">자사몰</option></select></div><div class="table"><table><thead id="head"></thead><tbody id="rows"></tbody></table></div><div id="empty" class="empty" style="display:none">검색 결과가 없습니다.</div></div></div><script>
const tenant='__legacy__';let data=[],tab='product',sortKey='created_at',sortAsc=false;
async function api(p){const r=await fetch(p,{credentials:'same-origin'}),d=await r.json();if(!r.ok)throw Error(d.detail||r.status);return d}function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function channelText(v){return({naver:'네이버',coupang:'쿠팡',own_store:'자사몰'})[v]||v}function setTab(v){tab=v;productTab.classList.toggle('on',v==='product');skuTab.classList.toggle('on',v==='sku');render()}function sort(k){sortAsc=sortKey===k?!sortAsc:true;sortKey=k;render()}function flat(){return data.flatMap(p=>p.skus.map(s=>({...s,product_name:p.name,product_code:p.product_code,product_status:p.status,created_at:p.created_at})))}function match(x){const needle=q.value.trim().toLowerCase(),blob=JSON.stringify(x).toLowerCase();return(!needle||blob.includes(needle))&&(!status.value||(tab==='product'?x.status:x.status)===status.value)&&(!channel.value||(tab==='product'?x.skus.some(s=>s.channels.some(c=>c.channel===channel.value)):x.channels.some(c=>c.channel===channel.value)))}function sorted(a){return a.sort((x,y)=>{let A=x[sortKey]??'',B=y[sortKey]??'';return(A>B?1:A<B?-1:0)*(sortAsc?1:-1)})}
function render(){let items=sorted((tab==='product'?data:flat()).filter(match));if(tab==='product'){head.innerHTML='<tr><th onclick="sort(\'product_code\')">상품코드</th><th onclick="sort(\'name\')">상품명</th><th>SKU</th><th>상태</th><th>네이버</th><th>쿠팡</th><th>자사몰</th><th onclick="sort(\'updated_at\')">수정일</th><th>관리</th></tr>';rows.innerHTML=items.map(p=>`<tr><td class="code">${esc(p.product_code)}</td><td><a href="/product-registration?product_id=${p.id}"><b>${esc(p.name)}</b></a></td><td>${p.skus.length}</td><td><span class="pill">${esc(p.status)}</span></td>${['naver','coupang','own_store'].map(c=>`<td>${p.skus.some(s=>s.channels.some(x=>x.channel===c))?'<span class="ok">연결</span>':'<span class="muted">미연결</span>'}</td>`).join('')}<td>${esc((p.updated_at||'').slice(0,10))}</td><td><button class="danger" onclick="deleteProduct('${p.id}')">삭제</button></td></tr>`).join('')}else{head.innerHTML='<tr><th onclick="sort(\'sku_code\')">SKU 코드</th><th>상품</th><th onclick="sort(\'option_value\')">옵션</th><th>판매단위</th><th onclick="sort(\'barcode\')">바코드</th><th>상태</th><th>채널 연결</th></tr>';rows.innerHTML=items.map(s=>`<tr><td class="code">${esc(s.sku_code)}</td><td>${esc(s.product_name)}<div class="muted code">${esc(s.product_code)}</div></td><td>${esc(s.option_value||'기본')}</td><td>${esc(({each:'낱개',box:'박스',set:'세트'})[s.sales_unit]||s.sales_unit)}</td><td>${esc(s.barcode||'미등록')}</td><td><span class="pill">${esc(s.status)}</span></td><td>${s.channels.length?s.channels.map(c=>`<span class="pill">${channelText(c.channel)} · ${esc(c.status)}</span>`).join(' '):'<span class="muted">미연결</span>'}</td></tr>`).join('')}empty.style.display=items.length?'none':'block'}
async function deleteProduct(id){const p=data.find(x=>x.id===id);if(!p)return;const listings=p.skus.reduce((n,s)=>n+s.channels.length,0),warning=`${p.name}\n상품코드: ${p.product_code}\n연결 SKU: ${p.skus.length}개\n쇼핑몰 연결: ${listings}개\n\n삭제하면 관련 자료도 함께 삭제되며 되돌릴 수 없습니다.`;if(!confirm(warning+'\n\n계속하시겠습니까?'))return;const typed=prompt(`최종 확인을 위해 상품코드 ${p.product_code} 를 정확히 입력하세요.`);if(typed===null)return;if(typed!==p.product_code){alert('상품코드가 일치하지 않아 삭제하지 않았습니다.');return}try{const r=await fetch(`/api/v1/commerce-catalog/products/${p.id}?tenant_id=${tenant}`,{method:'DELETE',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirm_product_code:typed,delete_linked_skus:p.skus.length>0})}),d=await r.json();if(!r.ok)throw Error(d.detail||r.status);data=data.filter(x=>x.id!==p.id);summary.textContent=`상품 ${data.length}개 · SKU ${flat().length}개 · ${d.product_code} 삭제 완료`;render()}catch(e){alert('삭제하지 못했습니다: '+e)}}
async function init(){try{const ws=await api(`/api/v1/business/workspaces?tenant_id=${tenant}`),w=ws.find(x=>x.slug==='commerce-ai')||ws[0];if(!w)throw Error('Workspace가 없습니다.');data=await api(`/api/v1/commerce-catalog/rows?tenant_id=${tenant}&workspace_id=${w.id}`);summary.textContent=`상품 ${data.length}개 · SKU ${flat().length}개 · 기존 코드 보존 / 신규 코드 자동 발급`;render()}catch(e){summary.textContent='로그인 후 다시 열어주세요. '+e}}init();
</script></body></html>'''

@router.get("/commerce-catalog", response_class=HTMLResponse, include_in_schema=False)
def commerce_catalog_page():
    return HTMLResponse(HTML, headers={"Cache-Control": "no-store", "X-Content-Type-Options": "nosniff"})
