from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter()

HTML = r'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>상품관리 센터</title><style>
*{box-sizing:border-box}body{margin:0;background:#0b0f17;color:#e5e7eb;font-family:Inter,Pretendard,system-ui,sans-serif}.wrap{max-width:1450px;margin:auto;padding:28px}a{color:#bfdbfe;text-decoration:none}.top,.tabs,.toolbar{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.top{justify-content:space-between;margin-bottom:18px}.tabs{margin:14px 0}.tabs button,.toolbar button{border:1px solid #35445a;background:#182337;color:white;border-radius:9px;padding:9px 13px}.tabs button.on{background:#e5e7eb;color:#111827}.card{background:#111827;border:1px solid #263247;border-radius:15px;overflow:hidden}.toolbar{padding:14px;border-bottom:1px solid #263247}.toolbar input,.toolbar select{background:#0b1220;color:#fff;border:1px solid #35445a;border-radius:9px;padding:10px}.toolbar input{min-width:320px;flex:1}.table{overflow:auto}table{border-collapse:collapse;width:100%;min-width:1240px}th,td{border-bottom:1px solid #253044;padding:12px;text-align:left;font-size:13px}th{color:#8ea0b7;background:#0d1421;cursor:pointer}.code{font-family:ui-monospace,monospace;color:#bfdbfe}.muted{color:#8ea0b7}.pill{border:1px solid #35445a;border-radius:999px;padding:3px 7px;font-size:11px}.ok{color:#a7f3d0}.danger{border:1px solid #7f1d1d;background:#3f1519;color:#fecaca;border-radius:8px;padding:6px 10px;cursor:pointer}.danger:hover{background:#7f1d1d}.empty{padding:35px;text-align:center;color:#8ea0b7}.summary{margin:8px 0 16px;color:#8ea0b7}@media(max-width:700px){.wrap{padding:16px}.toolbar input{min-width:100%}}
</style></head><body><div class="wrap"><div class="top"><div><h1 style="margin:0">상품관리 센터</h1><div class="muted">상품·SKU·가격·재고·콘텐츠·판매채널 통합 기준</div></div><div><a href="/dashboard">대시보드</a> · <a href="/product-registration">＋ 신규 상품 등록</a></div></div><div class="summary" id="summary">불러오는 중…</div><div class="tabs"><button id="productTab" class="on" onclick="setTab('product')">상품 목록</button><button id="skuTab" onclick="setTab('sku')">SKU 목록</button></div><div class="card"><div class="toolbar"><input id="q" placeholder="상품코드 · SKU · 상품명 · 옵션 · 바코드 통합검색" oninput="render()"><select id="status" onchange="render()"><option value="">전체 상태</option><option value="draft">초안</option><option value="active">활성</option><option value="inactive">비활성</option></select><select id="channel" onchange="render()"><option value="">전체 채널</option><option value="naver">네이버</option><option value="coupang">쿠팡</option><option value="own_store">자사몰</option></select></div><div class="table"><table><thead id="head"></thead><tbody id="rows"></tbody></table></div><div id="empty" class="empty" style="display:none">검색 결과가 없습니다.</div></div></div><script>
const tenant='__legacy__';let data=[],tab='product',sortKey='created_at',sortAsc=false;
async function api(p){const r=await fetch(p,{credentials:'same-origin'}),d=await r.json();if(!r.ok)throw Error(d.detail||r.status);return d}function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function channelText(v){return({naver:'네이버',coupang:'쿠팡',own_store:'자사몰'})[v]||v}function setTab(v){tab=v;productTab.classList.toggle('on',v==='product');skuTab.classList.toggle('on',v==='sku');render()}function sort(k){sortAsc=sortKey===k?!sortAsc:true;sortKey=k;render()}function flat(){return data.flatMap(p=>p.skus.map(s=>({...s,product_name:p.name,product_code:p.product_code,product_status:p.status,created_at:p.created_at})))}function match(x){const needle=q.value.trim().toLowerCase(),blob=JSON.stringify(x).toLowerCase();return(!needle||blob.includes(needle))&&(!status.value||(tab==='product'?x.status:x.status)===status.value)&&(!channel.value||(tab==='product'?x.skus.some(s=>s.channels.some(c=>c.channel===channel.value)):x.channels.some(c=>c.channel===channel.value)))}function sorted(a){return a.sort((x,y)=>{let A=x[sortKey]??'',B=y[sortKey]??'';return(A>B?1:A<B?-1:0)*(sortAsc?1:-1)})}
function render(){let items=sorted((tab==='product'?data:flat()).filter(match));if(tab==='product'){head.innerHTML='<tr><th onclick="sort(\'product_code\')">상품코드</th><th onclick="sort(\'name\')">상품명</th><th>SKU</th><th>상태</th><th>네이버</th><th>쿠팡</th><th>자사몰</th><th onclick="sort(\'updated_at\')">수정일</th><th>관리</th></tr>';rows.innerHTML=items.map(p=>`<tr><td class="code">${esc(p.product_code)}</td><td><a href="/commerce-catalog/product/${p.id}"><b>${esc(p.name)}</b></a></td><td>${p.skus.length}</td><td><span class="pill">${esc(p.status)}</span></td>${['naver','coupang','own_store'].map(c=>`<td>${p.skus.some(s=>s.channels.some(x=>x.channel===c))?'<span class="ok">연결</span>':'<span class="muted">미연결</span>'}</td>`).join('')}<td>${esc((p.updated_at||'').slice(0,10))}</td><td><button class="danger" onclick="deleteProduct('${p.id}')">삭제</button></td></tr>`).join('')}else{head.innerHTML='<tr><th onclick="sort(\'sku_code\')">SKU 코드</th><th>상품</th><th onclick="sort(\'option_value\')">옵션</th><th>판매단위</th><th onclick="sort(\'barcode\')">바코드</th><th>상태</th><th>판매가</th><th>가용재고</th><th>채널 연결</th></tr>';rows.innerHTML=items.map(s=>`<tr><td class="code">${esc(s.sku_code)}</td><td>${esc(s.product_name)}<div class="muted code">${esc(s.product_code)}</div></td><td>${esc(s.option_value||'기본')}</td><td>${esc(({each:'낱개',box:'박스',set:'세트'})[s.sales_unit]||s.sales_unit)}</td><td>${esc(s.barcode||'미등록')}</td><td><span class="pill">${esc(s.status)}</span></td><td>${s.sale_price==null?'미등록':Number(s.sale_price).toLocaleString()+'원'}</td><td>${s.available_stock}${s.stock_warning?' · 주의':''}</td><td>${s.channels.length?s.channels.map(c=>`<span class="pill">${channelText(c.channel)} · ${esc(c.status)}</span>`).join(' '):'<span class="muted">미연결</span>'}</td></tr>`).join('')}empty.style.display=items.length?'none':'block'}
async function deleteProduct(id){const p=data.find(x=>x.id===id);if(!p)return;const listings=p.skus.reduce((n,s)=>n+s.channels.length,0),warning=`${p.name}\n상품코드: ${p.product_code}\n연결 SKU: ${p.skus.length}개\n쇼핑몰 연결: ${listings}개\n\n삭제하면 관련 자료도 함께 삭제되며 되돌릴 수 없습니다.`;if(!confirm(warning+'\n\n계속하시겠습니까?'))return;const typed=prompt(`최종 확인을 위해 상품코드 ${p.product_code} 를 정확히 입력하세요.`);if(typed===null)return;if(typed!==p.product_code){alert('상품코드가 일치하지 않아 삭제하지 않았습니다.');return}try{const r=await fetch(`/api/v1/commerce-catalog/products/${p.id}?tenant_id=${tenant}`,{method:'DELETE',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirm_product_code:typed,delete_linked_skus:p.skus.length>0})}),d=await r.json();if(!r.ok)throw Error(d.detail||r.status);data=data.filter(x=>x.id!==p.id);summary.textContent=`상품 ${data.length}개 · SKU ${flat().length}개 · ${d.product_code} 삭제 완료`;render()}catch(e){alert('삭제하지 못했습니다: '+e)}}
async function init(){try{const ws=await api(`/api/v1/business/workspaces?tenant_id=${tenant}`),w=ws.find(x=>x.slug==='commerce-ai')||ws[0];if(!w)throw Error('Workspace가 없습니다.');data=await api(`/api/v1/commerce-catalog/rows?tenant_id=${tenant}&workspace_id=${w.id}`);summary.textContent=`상품 ${data.length}개 · SKU ${flat().length}개 · 기존 코드 보존 / 신규 코드 자동 발급`;render()}catch(e){summary.textContent='로그인 후 다시 열어주세요. '+e}}init();
</script></body></html>'''

DETAIL_HTML = r'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>상품 상세·수정</title><style>
*{box-sizing:border-box}body{margin:0;background:#0b0f17;color:#e5e7eb;font-family:Inter,Pretendard,system-ui,sans-serif}.wrap{max-width:1260px;margin:auto;padding:28px}a{color:#bfdbfe;text-decoration:none}.top{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;flex-wrap:wrap}.muted{color:#8ea0b7}.code{font-family:ui-monospace,monospace;color:#bfdbfe}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin:22px 0}.tabs button{border:1px solid #35445a;background:#182337;color:white;border-radius:9px;padding:10px 14px;cursor:pointer}.tabs button.on{background:#e5e7eb;color:#111827}.panel{display:none}.panel.on{display:block}.card{background:#111827;border:1px solid #263247;border-radius:15px;padding:20px;margin-bottom:16px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.grid.three{grid-template-columns:repeat(3,minmax(0,1fr))}label{display:block;color:#aab7ca;font-size:13px;margin-bottom:6px}input,select,textarea{width:100%;background:#0b1220;color:#fff;border:1px solid #35445a;border-radius:9px;padding:10px}textarea{min-height:92px;resize:vertical}.actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-top:16px}.primary,.secondary{border:0;border-radius:9px;padding:10px 15px;cursor:pointer}.primary{background:#2563eb;color:#fff}.secondary{background:#233149;color:#fff}.ok{color:#a7f3d0}.warn{color:#fcd34d}.metric{font-size:18px;font-weight:700}.sku-title{display:flex;justify-content:space-between;gap:12px;margin-bottom:14px}.link-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.link-card{display:block;background:#111827;border:1px solid #263247;border-radius:13px;padding:18px}.channel{border-top:1px solid #263247;padding-top:15px;margin-top:15px}@media(max-width:760px){.wrap{padding:16px}.grid,.grid.three,.link-grid{grid-template-columns:1fr}}
</style></head><body><div class="wrap"><div class="top"><div><a href="/commerce-catalog">← 상품관리 센터</a><h1 id="title" style="margin:10px 0 4px">상품 상세·수정</h1><div id="subtitle" class="muted">상품을 불러오는 중…</div></div><a href="/product-registration">＋ 신규 상품 등록</a></div><div class="tabs"><button class="on" data-tab="base" onclick="showTab('base')">기본정보</button><button data-tab="sku" onclick="showTab('sku')">옵션·SKU·가격·재고</button><button data-tab="content" onclick="showTab('content')">상품 콘텐츠</button><button data-tab="channel" onclick="showTab('channel')">판매채널</button></div>
<section id="base" class="panel on"><div class="card"><h2>상품 기본정보</h2><div class="grid"><div><label>상품명 *</label><input id="name"></div><div><label>상품코드</label><input id="productCode" disabled></div><div><label>카테고리</label><input id="category"></div><div><label>상태</label><select id="productStatus"><option value="draft">초안</option><option value="active">활성</option><option value="inactive">비활성</option></select></div><div><label>브랜드</label><input id="brand"></div><div><label>모델명</label><input id="modelName"></div><div><label>제조사</label><input id="manufacturer"></div><div><label>원산지</label><input id="origin"></div><div><label>공급처</label><input id="supplier"></div></div><div style="margin-top:14px"><label>상품 설명</label><textarea id="description"></textarea></div><div class="actions"><button class="primary" onclick="saveBase()">변경사항 저장</button><span id="baseStatus"></span></div></div></section>
<section id="sku" class="panel"><div class="card"><div class="sku-title"><div><h2 style="margin:0">옵션·SKU·가격·기본 재고</h2><div class="muted">재고 수량은 1단계 기본관리 값이며 주문 자동 차감은 이후 단계입니다.</div></div><button class="secondary" onclick="addSku()">＋ SKU 추가</button></div><div id="skuRows"></div></div></section>
<section id="content" class="panel"><div class="card"><h2>상품 콘텐츠 제작</h2><p class="muted">신규 등록과 별도로 기존 상품의 FACT·원본·이미지·상세페이지를 관리합니다.</p><div class="link-grid"><a id="factLink" class="link-card"><b>FACT·원본 자료</b><p class="muted">확인된 사실과 원본 파일 관리</p></a><a id="imageLink" class="link-card"><b>이미지 콘텐츠</b><p class="muted">이미지 FACT와 제작 흐름</p></a><a id="detailLink" class="link-card"><b>상세페이지</b><p class="muted">설명문과 상세페이지 제작</p></a></div></div></section>
<section id="channel" class="panel"><div class="card"><h2>판매채널 기본관리</h2><p class="muted">네이버·쿠팡·자사몰의 연결 번호와 상태를 SKU별로 관리합니다. 전체 등록항목과 엑셀 연동은 2단계입니다.</p><div id="channelRows"></div></div></section></div><script>
const tenant='__legacy__',productId=decodeURIComponent(location.pathname.split('/').pop());let product=null;
const $=id=>document.getElementById(id),val=id=>$(id).value,clean=v=>v===''?null:v,number=v=>v===''?null:Number(v),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function request(path,options={}){const r=await fetch(path,{credentials:'same-origin',...options}),d=await r.json();if(!r.ok)throw Error(d.detail||r.status);return d}
function showTab(id){document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('on',x.id===id));document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('on',x.dataset.tab===id))}
function skuFields(s,prefix){return `<div class="grid three"><div><label>SKU 코드</label><input value="${esc(s.sku_code||'자동 발급')}" disabled></div><div><label>SKU명 *</label><input id="${prefix}name" value="${esc(s.name||'')}"></div><div><label>옵션값</label><input id="${prefix}option" value="${esc(s.option_value||'')}"></div><div><label>바코드</label><input id="${prefix}barcode" value="${esc(s.barcode||'')}"></div><div><label>판매단위</label><select id="${prefix}unit"><option value="each" ${s.sales_unit==='each'?'selected':''}>낱개</option><option value="box" ${s.sales_unit==='box'?'selected':''}>박스</option><option value="set" ${s.sales_unit==='set'?'selected':''}>세트</option></select></div><div><label>상태</label><select id="${prefix}status"><option value="draft" ${s.status==='draft'?'selected':''}>초안</option><option value="active" ${s.status==='active'?'selected':''}>활성</option><option value="inactive" ${s.status==='inactive'?'selected':''}>비활성</option></select></div><div><label>매입원가</label><input type="number" min="0" id="${prefix}cost" value="${s.purchase_cost??''}"></div><div><label>정상 판매가</label><input type="number" min="0" id="${prefix}list" value="${s.list_price??''}"></div><div><label>할인·현재 판매가</label><input type="number" min="0" id="${prefix}sale" value="${s.sale_price??''}"></div><div><label>현재고</label><input type="number" min="0" id="${prefix}current" value="${s.current_stock??0}"></div><div><label>가용재고</label><input type="number" min="0" id="${prefix}available" value="${s.available_stock??0}"></div><div><label>안전재고</label><input type="number" min="0" id="${prefix}safety" value="${s.safety_stock??0}"></div><div><label>입고 예정</label><input type="number" min="0" id="${prefix}incoming" value="${s.incoming_stock??0}"></div><div><label>보관 위치</label><input id="${prefix}location" value="${esc(s.storage_location||'')}"></div></div>`}
function skuBody(prefix){return{name:val(prefix+'name'),option_value:clean(val(prefix+'option')),barcode:clean(val(prefix+'barcode')),sales_unit:val(prefix+'unit'),status:val(prefix+'status'),purchase_cost:number(val(prefix+'cost')),list_price:number(val(prefix+'list')),sale_price:number(val(prefix+'sale')),current_stock:Number(val(prefix+'current')||0),available_stock:Number(val(prefix+'available')||0),safety_stock:Number(val(prefix+'safety')||0),incoming_stock:Number(val(prefix+'incoming')||0),storage_location:clean(val(prefix+'location'))}}
function renderSkus(){$('skuRows').innerHTML=product.skus.map((s,i)=>{const p=`s${i}_`;return `<div class="card"><div class="sku-title"><b class="code">${esc(s.sku_code)}</b><span class="${s.stock_warning?'warn':'ok'}">${s.stock_warning?'안전재고 확인':'재고 정상'}</span></div>${skuFields(s,p)}<div class="actions"><button class="primary" onclick="saveSku('${s.id}',${i})">SKU 저장</button><span id="${p}msg"></span>${s.margin==null?'':`<span class="muted">예상 마진 ${Number(s.margin).toLocaleString()}원 · ${s.margin_rate}%</span>`}</div></div>`}).join('')||'<div class="muted">등록된 SKU가 없습니다.</div>'}
function renderChannels(){$('channelRows').innerHTML=product.skus.map((s,i)=>`<div class="card"><b>${esc(s.name)}</b><div class="code muted">${esc(s.sku_code)}</div>${['naver','coupang','own_store'].map(c=>{const x=s.channels.find(v=>v.channel===c)||{},p=`c${i}_${c}_`;return `<div class="channel"><h3>${{naver:'네이버',coupang:'쿠팡',own_store:'자사몰'}[c]}</h3><div class="grid three"><div><label>연결 상태</label><select id="${p}status">${['unlinked','linked','pending','active','error','stopped'].map(v=>`<option value="${v}" ${x.status===v?'selected':''}>${v}</option>`).join('')}</select></div><div><label>채널 상품번호</label><input id="${p}product" value="${esc(x.external_product_id||'')}"></div><div><label>채널 SKU 번호</label><input id="${p}sku" value="${esc(x.external_sku_id||'')}"></div><div><label>채널 상품명</label><input id="${p}name" value="${esc(x.channel_product_name||'')}"></div><div><label>채널 판매가</label><input type="number" min="0" id="${p}price" value="${x.channel_price??''}"></div></div><div class="actions"><button class="secondary" onclick="saveChannel('${s.id}','${c}','${p}')">채널 정보 저장</button><span id="${p}msg"></span></div></div>`}).join('')}</div>`).join('')||'<div class="muted">판매채널을 연결하려면 SKU를 먼저 등록하세요.</div>'}
function bind(){$('title').textContent=product.name;$('subtitle').innerHTML=`<span class="code">${esc(product.product_code)}</span> · 기존 상품 상세·수정`;$('name').value=product.name;$('productCode').value=product.product_code;$('category').value=product.category||'';$('productStatus').value=product.status;$('brand').value=product.brand||'';$('modelName').value=product.model_name||'';$('manufacturer').value=product.manufacturer||'';$('origin').value=product.country_of_origin||'';$('supplier').value=product.supplier_name||'';$('description').value=product.description||'';$('factLink').href=`/product-registration?product_id=${product.id}`;$('imageLink').href=`/image-assets?product_id=${product.id}`;$('detailLink').href=`/detail-pages?product_id=${product.id}`;renderSkus();renderChannels()}
async function init(){try{product=await request(`/api/v1/commerce-catalog/products/${productId}?tenant_id=${tenant}`);bind()}catch(e){$('subtitle').textContent='상품을 불러오지 못했습니다: '+e}}
async function saveBase(){try{await request(`/api/v1/commerce-catalog/products/${product.id}?tenant_id=${tenant}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:val('name'),status:val('productStatus'),description:clean(val('description')),category:clean(val('category')),brand:clean(val('brand')),model_name:clean(val('modelName')),manufacturer:clean(val('manufacturer')),country_of_origin:clean(val('origin')),supplier_name:clean(val('supplier'))})});$('baseStatus').innerHTML='<span class="ok">변경사항 저장 완료</span>';product=await request(`/api/v1/commerce-catalog/products/${productId}?tenant_id=${tenant}`);bind()}catch(e){$('baseStatus').textContent=String(e)}}
async function saveSku(id,i){const p=`s${i}_`;try{await request(`/api/v1/commerce-catalog/skus/${id}?tenant_id=${tenant}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(skuBody(p))});$(p+'msg').innerHTML='<span class="ok">저장 완료</span>';product=await request(`/api/v1/commerce-catalog/products/${productId}?tenant_id=${tenant}`);renderSkus();renderChannels()}catch(e){$(p+'msg').textContent=String(e)}}
async function addSku(){const name=prompt('새 SKU 이름을 입력하세요.');if(!name)return;const option=prompt('옵션값을 입력하세요. 옵션이 없으면 비워두세요.')||'';const body={name,option_value:clean(option),barcode:null,sales_unit:'each',status:'active',purchase_cost:null,list_price:null,sale_price:null,current_stock:0,available_stock:0,safety_stock:0,incoming_stock:0,storage_location:null};try{await request(`/api/v1/commerce-catalog/products/${product.id}/skus?tenant_id=${tenant}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});product=await request(`/api/v1/commerce-catalog/products/${productId}?tenant_id=${tenant}`);renderSkus();renderChannels()}catch(e){alert('SKU를 추가하지 못했습니다: '+e)}}
async function saveChannel(skuId,c,p){try{await request(`/api/v1/commerce-catalog/skus/${skuId}/channels/${c}?tenant_id=${tenant}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel:c,status:val(p+'status'),external_product_id:clean(val(p+'product')),external_sku_id:clean(val(p+'sku')),channel_product_name:clean(val(p+'name')),channel_price:number(val(p+'price'))})});$(p+'msg').innerHTML='<span class="ok">저장 완료</span>'}catch(e){$(p+'msg').textContent=String(e)}}init();
</script></body></html>'''

@router.get("/commerce-catalog", response_class=HTMLResponse, include_in_schema=False)
def commerce_catalog_page():
    return HTMLResponse(HTML, headers={"Cache-Control": "no-store", "X-Content-Type-Options": "nosniff"})


@router.get("/commerce-catalog/product/{product_id}", response_class=HTMLResponse, include_in_schema=False)
def commerce_product_page(product_id: str):
    return HTMLResponse(DETAIL_HTML, headers={"Cache-Control": "no-store", "X-Content-Type-Options": "nosniff"})
