from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter()

HTML = r'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>상세페이지 생성 | AI Business OS</title>
<style>
*{box-sizing:border-box}body{margin:0;font-family:Inter,Pretendard,system-ui,sans-serif;background:#f4f6fa;color:#172033}.top{height:64px;background:#fff;border-bottom:1px solid #e1e6ee;display:flex;align-items:center;padding:0 22px;gap:18px;position:sticky;top:0;z-index:10}.top a{text-decoration:none;color:#64748b}.brand{font-weight:900}.session{margin-left:auto;color:#64748b;font-size:13px}.login{display:flex;gap:8px}.login input{width:240px}
.workspace{display:grid;grid-template-columns:300px minmax(440px,1fr) 320px;min-height:calc(100vh - 64px)}.left,.right{background:#fff;padding:18px;overflow:auto}.left{border-right:1px solid #e1e6ee}.right{border-left:1px solid #e1e6ee}.center{padding:20px;overflow:auto}.label{font-size:12px;font-weight:800;color:#667085;margin:12px 0 6px}.muted{font-size:12px;color:#7b8798}select,input,textarea{width:100%;padding:10px;border:1px solid #d7dee8;border-radius:9px;background:#fff}textarea{min-height:90px}.btn{border:0;border-radius:9px;padding:10px 12px;font-weight:800;cursor:pointer}.primary{background:#3559e0;color:#fff}.ghost{background:#eef2ff;color:#3047a2}.soft{background:#f2f4f7;color:#344054}.full{width:100%}.row{display:flex;gap:8px}.row>*{flex:1}
.swatches{display:flex;gap:6px;margin-top:8px}.swatch{width:26px;height:26px;border-radius:8px;border:1px solid rgba(0,0,0,.08)}.sections{display:grid;gap:7px;margin-top:8px}.section-item{border:1px solid #e0e5ed;border-radius:10px;padding:9px;background:#fff;display:flex;align-items:center;gap:8px;cursor:grab}.section-item .name{flex:1;font-size:13px}.section-item.disabled{opacity:.45}.state{font-size:10px;padding:4px 6px;border-radius:999px;background:#f2f4f7}.preview-shell{max-width:760px;margin:0 auto;background:#fff;border:1px solid #e0e5ed;border-radius:18px;overflow:hidden;box-shadow:0 10px 40px rgba(18,36,70,.08)}.preview-toolbar{display:flex;justify-content:space-between;align-items:center;padding:12px 16px;border-bottom:1px solid #e8ecf2}.preview{min-height:900px;background:#fff}.block{padding:44px 42px;border-bottom:1px solid #edf0f4}.block.hero{padding:64px 42px;background:linear-gradient(135deg,var(--surface),var(--background))}.block h2{font-size:26px;margin:0 0 12px}.block h3{font-size:20px;margin:0 0 10px}.block p{line-height:1.65;color:var(--text)}.tag{display:inline-block;border-radius:999px;padding:6px 9px;background:var(--surface);color:var(--primary);font-size:12px;font-weight:800;margin:3px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.mini{border:1px solid #e3e7ec;border-radius:12px;padding:12px}.notice{background:#fffaeb;color:#7a5a00;padding:11px;border-radius:10px}.qa-item{padding:9px 0;border-bottom:1px solid #edf0f4;font-size:12px}.pass{color:#16803a}.review{color:#9a6700}.fail{color:#b42318}.version{font-size:12px;background:#f2f4f7;padding:5px 7px;border-radius:7px}.right h3,.left h3{margin:0 0 8px}.actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}@media(max-width:1100px){.workspace{grid-template-columns:260px 1fr}.right{grid-column:1/-1;border-left:0;border-top:1px solid #e1e6ee}}@media(max-width:760px){.workspace{display:block}.left,.right{border:0}.center{padding:10px}.block{padding:32px 22px}.cards{grid-template-columns:1fr}}
</style></head><body>
<div class="top"><a href="/dashboard">← 대시보드</a><div class="brand">AI Business OS · 상세페이지 생성</div><div class="session" id="sessionStatus">연결 확인 중</div><div class="login" id="loginBox"><input id="token" type="password" placeholder="Bearer token"><button class="btn primary" onclick="connect()">연결</button></div></div>
<div class="workspace"><aside class="left"><h3>제작 설정</h3><div class="muted">템플릿, 브랜드, 판매 흐름을 선택하고 섹션 순서를 드래그하세요.</div>
<div class="label">상품</div><select id="product"></select><div class="label">판매채널</div><select id="channel"><option value="naver-smartstore">네이버 스마트스토어</option><option value="own-store">자사몰</option><option value="open-market">오픈마켓</option><option value="b2b">B2B</option></select><div class="row"><div><div class="label">페이지 길이</div><select id="pageLength"><option value="long">LONG</option><option value="short">SHORT</option></select></div><div><div class="label">Visual Style</div><select id="visualStyle"><option value="natural">Natural</option><option value="clean">Clean</option><option value="premium">Premium</option><option value="technical">Technical</option></select></div></div>
<button class="btn primary full" style="margin-top:12px" onclick="createAndPrepare()">새 상세페이지 만들기</button>
<div class="label">현재 작업</div><select id="jobs" onchange="openJob(this.value)"></select>
<div class="label">브랜드 스타일 시트</div><select id="brandStyle" onchange="changeBrand()"></select><div class="swatches" id="swatches"></div>
<div class="label">템플릿</div><select id="template" onchange="changeTemplate()"><option value="A_PRACTICAL_TRUST">A — 실용·신뢰형</option><option value="B_LIFESTYLE">B — 라이프스타일형</option><option value="C_TECHNICAL">C — 정보·기술형</option></select>
<div class="label">페이지 전략</div><select id="strategy" onchange="changeStrategy()"><option value="review_first">Review First</option><option value="standard">Standard</option><option value="specs_first">Specs First</option><option value="lifestyle_first">Lifestyle First</option><option value="add_on_earlier">Add-on Earlier</option></select>
<div class="label">섹션 순서</div><div class="sections" id="sectionList"></div></aside>
<main class="center"><div class="preview-shell"><div class="preview-toolbar"><div><strong id="pageName">상세페이지 Preview</strong><div class="muted" id="pageMeta">P0/P1 미리보기</div></div><span class="version" id="version">V-</span></div><div class="preview" id="preview"><div class="block"><h3>작업을 선택하거나 새 상세페이지를 만들어 주세요.</h3></div></div></div></main>
<aside class="right"><h3>검토 · 수정</h3><div class="muted">블록을 클릭한 뒤 필요한 부분만 수정합니다.</div><div class="label">선택 블록</div><strong id="selectedType">-</strong><div class="label">레이아웃</div><input id="layout" disabled><div class="label">헤드라인</div><input id="headline" placeholder="COPY 섹션만 편집 가능"><div class="label">본문</div><textarea id="body" placeholder="COPY 섹션만 편집 가능"></textarea><button class="btn ghost full" onclick="saveSection()">선택 블록 수정</button>
<div class="label">자연어 수정 요청</div><textarea id="revision" placeholder="예: 리뷰를 더 위로 올려줘"></textarea><button class="btn ghost full" onclick="applyRevision()">수정 요청 적용</button>
<div class="actions"><button class="btn soft" onclick="runQA()">QA 검사</button><button class="btn primary" onclick="approve()">최종 승인</button></div><button class="btn ghost full" style="margin-top:8px" onclick="exportCanva()">Canva 전달 패키지</button><div class="label">QA</div><div id="qa"></div></aside></div>
<script>
const tenant='__legacy__';let workspace=null,products=[],current=null,selected=null,dragId=null;
async function jf(url,opts={}){const r=await fetch(url,{credentials:'same-origin',...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);return d}
async function sessionOK(){return (await fetch('/api/v1/dashboard/session',{credentials:'same-origin'})).ok}async function connect(){const t=token.value.trim();if(t){const r=await fetch('/api/v1/dashboard/session',{method:'POST',credentials:'same-origin',headers:{Authorization:`Bearer ${t}`}});if(!r.ok){alert('인증 실패');return}}await init()}
async function init(){if(!(await sessionOK())){sessionStatus.textContent='로그인 필요';return}loginBox.style.display='none';sessionStatus.textContent='Connected';const ws=await jf(`/api/v1/business/workspaces?tenant_id=${tenant}`);workspace=ws.find(x=>x.slug==='commerce-ai')||ws[0];if(!workspace)return;products=await jf(`/api/v1/business/products?tenant_id=${tenant}&workspace_id=${workspace.id}`);product.innerHTML=products.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');await loadJobs();await loadStyles()}
async function loadStyles(){if(!workspace)return;const rows=await jf(`/api/v1/detail-pages/brand-styles?tenant_id=${tenant}&workspace_id=${workspace.id}`);brandStyle.innerHTML=rows.map(x=>`<option value="${x.id}">${x.name}</option>`).join('');renderSwatches(rows.find(x=>x.id===brandStyle.value)||rows[0])}
function renderSwatches(b){if(!b)return;swatches.innerHTML=[b.primary_color,b.secondary_color,b.accent_color,b.background_color,b.text_color].map(c=>`<span class="swatch" style="background:${c}" title="${c}"></span>`).join('')}
async function loadJobs(){const rows=await jf(`/api/v1/detail-pages/jobs?tenant_id=${tenant}`);jobs.innerHTML='<option value="">작업 선택</option>'+rows.map(x=>`<option value="${x.id}">${x.product_name||x.product_id} · ${x.status} · V${x.current_version_no}</option>`).join('');if(current){jobs.value=current.id}}
async function createAndPrepare(){const created=await jf(`/api/v1/detail-pages/jobs?tenant_id=${tenant}`,{method:'POST',body:JSON.stringify({workspace_id:workspace.id,product_id:product.value,channel:channel.value,page_length:pageLength.value})});current=await jf(`/api/v1/detail-pages/jobs/${created.id}/prepare?tenant_id=${tenant}`,{method:'POST',body:JSON.stringify({template_code:template.value,visual_style:visualStyle.value,page_strategy:strategy.value,brand_style_sheet_id:brandStyle.value||null})});render();await loadJobs()}
async function openJob(id){if(!id)return;current=await jf(`/api/v1/detail-pages/jobs/${id}?tenant_id=${tenant}`);render()}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function render(){if(!current||!current.current_version)return;const v=current.current_version;version.textContent=`V${v.version_no}`;pageName.textContent=current.product_name||'상세페이지';pageMeta.textContent=`${v.template?.name||''} · ${v.visual_style} · ${v.page_strategy} · ${current.status}`;template.value=v.template?.code||'A_PRACTICAL_TRUST';visualStyle.value=v.visual_style;strategy.value=v.page_strategy;if(v.brand_style){brandStyle.value=v.brand_style.id;renderSwatches(v.brand_style)}const secs=v.sections||[];sectionList.innerHTML=secs.map(s=>{const state=!s.is_enabled?'숨김':(s.qa_status||'review');return `<div class="section-item ${s.is_enabled?'':'disabled'}" draggable="true" data-id="${s.id}" onclick="selectSection('${s.id}')" ondragstart="dragId='${s.id}'" ondragover="event.preventDefault()" ondrop="dropSection('${s.id}')"><span>☰</span><span class="name">${s.section_type}</span><span class="state">${state}</span></div>`}).join('');preview.style.setProperty('--primary',v.brand_style?.primary_color||'#1F6B4F');preview.style.setProperty('--surface',v.brand_style?.surface_color||'#F5F7F6');preview.style.setProperty('--background',v.brand_style?.background_color||'#fff');preview.style.setProperty('--text',v.brand_style?.text_color||'#17211C');preview.innerHTML=secs.filter(s=>s.is_enabled).map(blockHtml).join('');renderQA(current.qa);if(selected){const found=secs.find(s=>s.id===selected.id);selected=found||null;fillInspector()} }
function blockHtml(s){const c=s.content||{};const cls=s.section_type==='HERO'?'block hero':'block';let inner=`<div class="muted">${s.section_type}</div><h2>${esc(c.headline||c.title||s.section_type)}</h2>`;if(c.subheadline)inner+=`<p>${esc(c.subheadline)}</p>`;if(c.body)inner+=`<p>${esc(c.body)}</p>`;if(c.product_specification)inner+=`<p><strong>확정 사양</strong><br>${esc(c.product_specification)}</p>`;if(c.usage)inner+=`<p><strong>사용 범위</strong><br>${esc(c.usage)}</p>`;if(c.specification)inner+=`<p><strong>제품 사양</strong><br>${esc(c.specification)}</p>`;if(c.usage_conditions)inner+=`<p><strong>사용 조건</strong><br>${esc(c.usage_conditions)}</p>`;if(c.note)inner+=`<div class="notice">${esc(c.note)}</div>`;if(c.items&&Array.isArray(c.items)){inner+='<div class="cards">'+c.items.slice(0,4).map(x=>`<div class="mini">${esc(typeof x==='string'?x:(x.name||x.review_text||JSON.stringify(x)))}</div>`).join('')+'</div>'}if(c.options&&Array.isArray(c.options)){inner+='<div class="cards">'+c.options.slice(0,3).map(x=>`<div class="mini"><strong>${esc(x.option_value||x.name)}</strong><div class="muted">${esc(x.sku_code||'')}</div></div>`).join('')+'</div>'}if(c.components&&Array.isArray(c.components)){inner+='<div class="cards">'+c.components.slice(0,6).map(x=>`<div class="mini">${esc(x.name)}</div>`).join('')+'</div>'}if(c.reviews&&Array.isArray(c.reviews)&&c.reviews.length){inner+='<div class="cards">'+c.reviews.slice(0,3).map(x=>`<div class="mini">★ ${esc(x.rating||'-')}<br>${esc(x.review_text)}</div>`).join('')+'</div>'}if(s.image_content_url)inner+=`<img src="${s.image_content_url}" style="width:100%;border-radius:12px;margin-top:12px">`;return `<section class="${cls}" onclick="selectSection('${s.id}')">${inner}</section>`}
function selectSection(id){const s=current.current_version.sections.find(x=>x.id===id);selected=s;fillInspector()}
function fillInspector(){if(!selected){selectedType.textContent='-';return}selectedType.textContent=`${selected.section_type} · ${selected.source_type}`;layout.value=selected.layout_variant||'';const c=selected.content||{};headline.value=c.headline||c.title||'';body.value=c.body||'';const editable=selected.source_type==='copy';headline.disabled=!editable;body.disabled=!editable}
async function saveSection(){if(!selected)return;const bodyData={layout_variant:layout.value};if(selected.source_type==='copy'){bodyData.headline=headline.value;bodyData.body=body.value}try{current=await jf(`/api/v1/detail-pages/jobs/${current.id}/sections/${selected.id}?tenant_id=${tenant}`,{method:'PUT',body:JSON.stringify(bodyData)});selected=null;render();await loadJobs()}catch(e){alert(e.message)}}
async function dropSection(targetId){if(!dragId||dragId===targetId)return;const secs=[...current.current_version.sections];const from=secs.findIndex(x=>x.id===dragId),to=secs.findIndex(x=>x.id===targetId);const [item]=secs.splice(from,1);secs.splice(to,0,item);current=await jf(`/api/v1/detail-pages/jobs/${current.id}/sections/reorder?tenant_id=${tenant}`,{method:'POST',body:JSON.stringify({section_ids:secs.map(x=>x.id)})});dragId=null;selected=null;render();await loadJobs()}
async function changeTemplate(){if(!current)return;current=await jf(`/api/v1/detail-pages/jobs/${current.id}/template?tenant_id=${tenant}`,{method:'POST',body:JSON.stringify({template_code:template.value})});render();await loadJobs()}
async function changeBrand(){const rows=await jf(`/api/v1/detail-pages/brand-styles?tenant_id=${tenant}&workspace_id=${workspace.id}`);renderSwatches(rows.find(x=>x.id===brandStyle.value));if(!current)return;current=await jf(`/api/v1/detail-pages/jobs/${current.id}/brand-style?tenant_id=${tenant}`,{method:'POST',body:JSON.stringify({brand_style_sheet_id:brandStyle.value})});render();await loadJobs()}
async function changeStrategy(){if(!current)return;current=await jf(`/api/v1/detail-pages/jobs/${current.id}/style?tenant_id=${tenant}`,{method:'POST',body:JSON.stringify({page_strategy:strategy.value,visual_style:visualStyle.value})});render();await loadJobs()}
async function applyRevision(){if(!current||!revision.value.trim())return;const d=await jf(`/api/v1/detail-pages/jobs/${current.id}/revision?tenant_id=${tenant}`,{method:'POST',body:JSON.stringify({instruction:revision.value.trim()})});current=d.job;revision.value='';render();await loadJobs();if(!d.applied)alert(d.revision.reason)}
async function runQA(){if(!current)return;const d=await jf(`/api/v1/detail-pages/jobs/${current.id}/qa?tenant_id=${tenant}`,{method:'POST',body:'{}'});current=d.job;render()}
function renderQA(q){if(!q){qa.innerHTML='';return}qa.innerHTML=`<div><strong>종합: ${q.summary}</strong></div>`+(q.items||[]).map(x=>`<div class="qa-item ${x.status.toLowerCase()}"><strong>${x.status}</strong> · ${esc(x.message)}${x.suggested_fix?`<div class="muted" style="margin-top:4px">권장: ${esc(x.suggested_fix)}</div>`:''}</div>`).join('')}
async function approve(){if(!current)return;try{const d=await jf(`/api/v1/detail-pages/jobs/${current.id}/approve?tenant_id=${tenant}`,{method:'POST',body:JSON.stringify({acknowledge_review:true})});current=d.job;render();await loadJobs()}catch(e){alert(e.message)}}
async function exportCanva(){if(!current)return;try{const d=await jf(`/api/v1/detail-pages/jobs/${current.id}/export/canva?tenant_id=${tenant}`,{method:'POST',body:'{}'});alert(`Canva 전달 패키지 준비 완료\nExport ID: ${d.export_id}`)}catch(e){alert(e.message)}}
init();
</script></body></html>'''

@router.get("/detail-pages", response_class=HTMLResponse)
def detail_pages_ui():
    return HTMLResponse(HTML)
