from __future__ import annotations

from starlette.middleware.base import BaseHTTPMiddleware
from starlette.responses import Response


GLOBAL_STYLE = r"""<style id="aios-global-style">
:root{--aios-nav:#14243b;--aios-blue:#2763dc;--aios-border:#dfe5ee}body{padding-left:224px!important}.side,.sidebar{display:none!important}.shell,.layout{grid-template-columns:1fr!important}
.aios-global-side{position:fixed;inset:0 auto 0 0;width:224px;z-index:900;background:var(--aios-nav);color:#dbe5f2;padding:20px 14px;overflow:auto;font-family:Inter,Pretendard,"Noto Sans KR",system-ui,sans-serif}.aios-global-brand{display:flex;align-items:center;gap:10px;padding:0 8px 18px;font-weight:800}.aios-global-logo{width:34px;height:34px;display:grid;place-items:center;border-radius:10px;background:#fff;color:#14243b}.aios-global-label{padding:16px 10px 5px;color:#8498b4;font-size:11px;font-weight:700}.aios-global-side a,.aios-global-side button{display:flex;width:100%;align-items:center;gap:9px;border:0;border-radius:9px;padding:10px;color:inherit;background:transparent;text-decoration:none;font:inherit;text-align:left;cursor:pointer}.aios-global-side a:hover,.aios-global-side a.active{background:var(--aios-blue);color:#fff}.aios-global-side button[disabled]{cursor:default;color:#8498b4}.aios-ready{margin-left:auto;font-size:10px;border:1px solid #526987;border-radius:999px;padding:2px 6px}
.aios-agent-launch{position:fixed;z-index:940;top:14px;right:18px;display:inline-flex;align-items:center;gap:7px;border-radius:999px;padding:10px 15px;background:var(--aios-blue);color:#fff!important;text-decoration:none;font:700 13px Inter,Pretendard,"Noto Sans KR",system-ui,sans-serif;box-shadow:0 8px 24px rgba(39,99,220,.28)}.aios-agent-launch:hover{background:#1f55bd}
.aios-mobile-head,.aios-mobile-bottom,.aios-mobile-drawer,.aios-drawer-shade{display:none}.aios-intro{position:fixed;inset:0;z-index:1200;display:grid;place-items:center;text-align:center;background:#14243b;color:#fff;opacity:1;visibility:visible;transition:opacity .4s ease,visibility .4s ease}.aios-intro.hidden{opacity:0;visibility:hidden;pointer-events:none}.aios-intro-logo{width:76px;height:76px;margin:0 auto 20px;display:grid;place-items:center;border:1px solid #fff;border-radius:22px;font-size:24px;font-weight:800;animation:aios-float 1.8s ease-in-out infinite alternate}.aios-intro h1{margin:0 0 10px;font-size:clamp(28px,5vw,48px)}.aios-intro p{margin:0 0 24px;color:#c8d6ea}.aios-intro button{border:1px solid #fff;border-radius:10px;padding:10px 18px;background:transparent;color:#fff;font-weight:800;cursor:pointer}@keyframes aios-float{to{transform:translateY(-7px)}}@media(prefers-reduced-motion:reduce){.aios-intro-logo{animation:none}}
@media(max-width:900px){body{padding:64px 0 72px!important}.aios-global-side{display:none}.aios-mobile-head{display:flex;position:fixed;inset:0 0 auto 0;height:58px;z-index:950;align-items:center;justify-content:space-between;padding:8px 12px;background:#14243b;color:#fff}.aios-mobile-head .aios-global-brand{padding:0}.aios-mobile-head button{border:0;background:transparent;color:#fff;font-size:22px;padding:8px}.aios-mobile-bottom{display:grid;grid-template-columns:repeat(4,1fr);position:fixed;inset:auto 0 0 0;z-index:950;background:#fff;border-top:1px solid var(--aios-border);padding:7px 4px}.aios-mobile-bottom a,.aios-mobile-bottom button{border:0;background:transparent;color:#334155;text-align:center;text-decoration:none;font-size:11px;padding:5px}.aios-mobile-bottom strong{display:block;font-size:17px}.aios-mobile-drawer{display:block;position:fixed;z-index:1001;top:0;bottom:0;right:0;width:min(86vw,340px);padding:18px;background:#14243b;color:#dbe5f2;overflow:auto;transform:translateX(105%);transition:transform .25s ease}.aios-mobile-drawer.open{transform:none}.aios-drawer-shade{position:fixed;z-index:1000;inset:0;background:rgba(0,0,0,.45)}.aios-drawer-shade.open{display:block}.aios-mobile-drawer .aios-global-side{display:block;position:static;width:auto;padding:0}.mobile{display:none!important}.main{padding:16px!important}}
@media(max-width:900px){.aios-agent-launch{top:auto;right:12px;bottom:76px;padding:10px 13px}}
</style>"""

NAV_CONTENT = r"""<div class="aios-global-brand"><span class="aios-global-logo">AI</span><span>AI Business OS</span></div><div class="aios-global-label">업무</div><a data-route="/business-home" href="/business-home">⌂ 오늘의 업무</a><a data-route="/commerce-catalog" href="/commerce-catalog">▣ 상품관리</a><a data-route="/product-registration" href="/product-registration">＋ 신규 상품 등록</a><a data-route="/products" href="/products">✦ 콘텐츠 제작</a><button disabled>판매 운영 <span class="aios-ready">준비 중</span></button><div class="aios-global-label">운영</div><button disabled>업무함·승인 <span class="aios-ready">준비 중</span></button><a data-route="/agent-workspace" href="/agent-workspace?task=new-product">◈ Agent에게 맡기기</a><a data-route="/operations" href="/operations">⚙ Agent 관리</a><a data-route="/dashboard" href="/dashboard">◷ 실행 기록·기존 운영</a><div class="aios-global-label">관리·기존 도구</div><a data-route="/image-assets" href="/image-assets">이미지 요소 자산</a><a data-route="/content-copy-studio" href="/content-copy-studio">콘텐츠 문안</a><a data-route="/template-maker" href="/template-maker">템플릿 제작</a><a data-route="/detail-page-builder" href="/detail-page-builder">상세페이지 생성</a><a data-route="/google-drive" href="/google-drive">Google Drive 연결</a>"""


def navigation_markup(show_intro: bool) -> str:
    intro = ""
    if show_intro:
        intro = r"""<div class="aios-intro" id="aiosIntro"><div><div class="aios-intro-logo">AI</div><h1>Welcome to AI Business OS</h1><p>사람과 Agent가 함께 일하는 새로운 업무 공간</p><button type="button" id="aiosIntroSkip">시작하기</button></div></div>"""
    return GLOBAL_STYLE + intro + f'''<aside class="aios-global-side" aria-label="전체 업무 메뉴">{NAV_CONTENT}</aside><a class="aios-agent-launch" id="aiosAgentLaunch" href="/agent-workspace">◈ Agent에게 요청</a><header class="aios-mobile-head"><div class="aios-global-brand"><span class="aios-global-logo">AI</span><span>AI Business OS</span></div><button type="button" data-aios-menu aria-label="전체 메뉴 열기">☰</button></header><div class="aios-drawer-shade" data-aios-close></div><aside class="aios-mobile-drawer" aria-label="모바일 전체 메뉴"><button type="button" data-aios-close style="float:right;border:0;background:transparent;color:inherit;font-size:22px">×</button><div class="aios-global-side">{NAV_CONTENT}</div></aside><nav class="aios-mobile-bottom" aria-label="모바일 핵심 메뉴"><a href="/business-home"><strong>⌂</strong>홈</a><a href="/commerce-catalog"><strong>▣</strong>상품관리</a><a href="/product-registration"><strong>＋</strong>신규등록</a><button type="button" data-aios-menu><strong>☰</strong>전체메뉴</button></nav><script id="aios-global-script">(function(){{const path=location.pathname;document.querySelectorAll('.aios-global-side a[data-route]').forEach(a=>{{const route=a.dataset.route;if(path===route||(route!='/business-home'&&path.startsWith(route+'/')))a.classList.add('active')}});const launch=document.getElementById('aiosAgentLaunch');if(launch){{const params=new URLSearchParams({{source_path:path}});let task='edit-product';if(path.startsWith('/product-registration'))task='new-product';else if(path.startsWith('/products')||path.includes('content')||path.includes('detail-page')||path.includes('image'))task='content';else if(path.includes('channel'))task='sales-channel';const match=path.match(/^\\/commerce-catalog\\/product\\/([^/]+)/);if(match)params.set('context_product_id',decodeURIComponent(match[1]));params.set('task',task);launch.href='/agent-workspace?'+params.toString();if(path==='/agent-workspace')launch.style.display='none'}}const drawer=document.querySelector('.aios-mobile-drawer'),shade=document.querySelector('.aios-drawer-shade');function toggle(open){{drawer&&drawer.classList.toggle('open',open);shade&&shade.classList.toggle('open',open)}}document.querySelectorAll('[data-aios-menu]').forEach(b=>b.onclick=()=>toggle(true));document.querySelectorAll('[data-aios-close]').forEach(b=>b.onclick=()=>toggle(false));const intro=document.getElementById('aiosIntro');if(intro){{const hide=()=>intro.classList.add('hidden');document.getElementById('aiosIntroSkip').onclick=hide;setTimeout(hide,4000)}}}})();</script>'''


class GlobalNavigationMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request, call_next):
        response = await call_next(request)
        if "text/html" not in response.headers.get("content-type", ""):
            return response
        body = b"".join([chunk async for chunk in response.body_iterator])
        html = body.decode("utf-8")
        if "aios-global-style" not in html and "<body" in html:
            marker = html.find(">", html.find("<body")) + 1
            html = html[:marker] + navigation_markup(request.url.path == "/business-home") + html[marker:]
        headers = dict(response.headers)
        headers.pop("content-length", None)
        return Response(html, status_code=response.status_code, headers=headers, media_type="text/html")
