"""Approved product detail draft (DEC-036 through DEC-040).

The page intentionally reuses the commerce catalog API and existing FACT,
image, and detail-page workspaces. Marketplace publication remains outside the
internal batch-save boundary.
"""

DETAIL_HTML_V2 = r'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>상품 상세·수정</title><style>
*{box-sizing:border-box}body{margin:0;background:#0b0f17;color:#e5e7eb;font-family:Inter,Pretendard,system-ui,sans-serif}.wrap{max-width:1320px;margin:auto;padding:28px}a{color:#bfdbfe;text-decoration:none}.top,.row,.actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.top{justify-content:space-between;align-items:flex-start}.muted{color:#8ea0b7}.code{font-family:ui-monospace,monospace;color:#bfdbfe}.tabs{display:flex;gap:5px;flex-wrap:wrap;margin:20px 0;border-bottom:1px solid #263247}.tabs button{border:0;border-bottom:2px solid transparent;background:transparent;color:#8ea0b7;padding:11px 12px;cursor:pointer}.tabs button.on{color:#fff;border-bottom-color:#60a5fa}.panel{display:none}.panel.on{display:block}.card{background:#111827;border:1px solid #263247;border-radius:14px;padding:18px;margin-bottom:15px}.control{display:grid;grid-template-columns:1fr auto;gap:14px;align-items:center}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.grid.three{grid-template-columns:repeat(3,minmax(0,1fr))}label{display:block;color:#aab7ca;font-size:13px;margin-bottom:6px}input,select,textarea{width:100%;background:#0b1220;color:#fff;border:1px solid #35445a;border-radius:9px;padding:10px}textarea{min-height:82px;resize:vertical}.primary,.secondary{border:0;border-radius:9px;padding:10px 14px;cursor:pointer}.primary{background:#2563eb;color:#fff}.secondary{background:#233149;color:#fff}.ok{color:#a7f3d0}.warn{color:#fcd34d}.bad{color:#fca5a5}.sku{border-top:1px solid #263247;padding-top:16px;margin-top:16px}.assets{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.slot{border:1px solid #263247;border-radius:12px;overflow:hidden}.preview{aspect-ratio:4/3;background:#0b1220;display:grid;place-items:center;text-align:center;color:#8ea0b7;overflow:hidden;cursor:zoom-in}.preview img{width:100%;height:100%;object-fit:cover;display:block}.preview.no-image{cursor:default}.lightbox{position:fixed;inset:0;background:rgba(0,0,0,.88);display:none;align-items:center;justify-content:center;padding:28px;z-index:100}.lightbox.on{display:flex}.lightbox img{max-width:96vw;max-height:92vh;object-fit:contain}.lightbox button{position:absolute;top:18px;right:18px;font-size:22px}.slot-body{padding:13px;min-height:104px}.slot-body .secondary{display:inline-flex;margin-top:10px}.empty{border-style:dashed}.proposal{background:#0b1220;border:1px solid #35445a;border-radius:10px;padding:14px;margin-top:14px}.footer{position:sticky;bottom:0;background:#0b0f17;border-top:1px solid #263247;padding:14px 0;display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}@media(max-width:760px){.wrap{padding:16px}.grid,.grid.three,.assets,.control{grid-template-columns:1fr}.footer{position:static}}
</style></head><body><div class="wrap">
<div class="top"><div><a href="/commerce-catalog">← 상품관리 센터</a><h1 id="title" style="margin:10px 0 4px">상품 상세·수정</h1><div id="subtitle" class="muted">불러오는 중…</div></div><div class="actions"><button class="secondary" onclick="readinessCheck()">등록 준비 점검</button><a class="secondary" href="/product-registration">＋ 신규 상품 등록</a></div></div>
<div class="card control"><div><b>실행 방식</b><div class="muted">사용자 직접 실행 · 설정 기반 자동화 · Agent 판단 실행이 같은 공통 기능을 사용합니다.</div></div><div class="actions"><button class="secondary" onclick="showSettings()">적용 설정 보기</button><label style="margin:0"><input id="agentEnabled" type="checkbox" checked style="width:auto"> Agent 실행 허용</label></div></div>
<div class="tabs"><button class="on" data-tab="info" onclick="showTab('info')">상품정보</button><button data-tab="sku" onclick="showTab('sku')">옵션·SKU</button><button data-tab="price" onclick="showTab('price')">가격·재고·배송</button><button data-tab="assets" onclick="showTab('assets')">등록 자료</button><button data-tab="content" onclick="showTab('content')">판매콘텐츠</button><button data-tab="channel" onclick="showTab('channel')">판매채널</button><button data-tab="history" onclick="showTab('history')">변경·작업이력</button></div>

<section id="info" class="panel on"><div class="card"><div class="top"><div><h2 style="margin:0">상품정보</h2><div class="muted">기본정보·확정 FACT와 설명정보를 분리해 관리합니다.</div></div><button class="secondary" onclick="showAiProposal()">AI 제안</button></div><div class="grid" style="margin-top:16px"><div><label>상품명 *</label><input id="name"></div><div><label>상품코드</label><input id="productCode" disabled></div><div><label>카테고리</label><input id="category"></div><div><label>상태</label><select id="productStatus"><option value="draft">초안</option><option value="active">활성</option><option value="inactive">비활성</option></select></div><div><label>브랜드</label><input id="brand"></div><div><label>모델명</label><input id="modelName"></div><div><label>제조사</label><input id="manufacturer"></div><div><label>원산지</label><input id="origin"></div><div><label>공급처</label><input id="supplier"></div><div><label>상품 설명</label><textarea id="description"></textarea></div><div><label>특징 (한 줄에 하나)</label><textarea id="features"></textarea></div><div><label>장점 (한 줄에 하나)</label><textarea id="advantages"></textarea></div><div><label>단점·제약 (한 줄에 하나)</label><textarea id="limitations"></textarea></div><div><label>추천 사용환경 (한 줄에 하나)</label><textarea id="recommendedUses"></textarea></div><div><label>주의정보·금지표현 (한 줄에 하나)</label><textarea id="cautions"></textarea></div></div><div id="aiProposal" class="proposal" style="display:none"><b>AI 제안 · 사용자 검토 전</b><p>확정 FACT를 근거로 제안하며 자동 저장하지 않습니다.</p><div class="actions"><button class="primary" onclick="acceptProposal()">채택</button><button class="secondary" onclick="acceptProposal()">수정 후 채택</button><button class="secondary" onclick="dismissProposal()">제외</button><a id="factEvidence" class="secondary">근거 보기</a></div></div></div></section>

<section id="sku" class="panel"><div class="card"><div class="top"><div><h2 style="margin:0">옵션·SKU</h2><div class="muted">기존 옵션·SKU·가격·재고 화면을 역할별로 나눴습니다. 상품코드는 유지합니다.</div></div><button class="secondary" onclick="addSku()">＋ SKU 추가</button></div><div id="skuIdentity"></div></div></section>
<section id="price" class="panel"><div class="card"><h2>가격·재고·배송</h2><p class="muted">SKU별 내부 가격과 기본 재고를 함께 저장합니다. 주문 자동 차감은 이후 단계이며 외부 가격변경은 실행하지 않습니다.</p><div id="skuCommercial"></div></div></section>
<section id="assets" class="panel"><div class="card"><div class="top"><div><h2 style="margin:0">등록 자료</h2><div class="muted">확정 Image FACT를 표시합니다. 이미지를 누르면 원본 비율로 확대됩니다.</div></div><a id="assetWorkspace" class="secondary">등록 자료 관리</a></div><div class="assets" style="margin-top:14px"><div class="slot"><div id="primaryPreview" class="preview no-image">대표이미지 없음</div><div class="slot-body"><b>대표이미지</b><div class="muted">확정된 RIGHT_45를 기본 대표로 사용</div><div class="actions"><a id="primaryReplace" class="secondary">교체</a><button class="secondary" disabled>삭제(보관처리)</button></div></div></div><div class="slot"><div id="right45Preview" class="preview no-image">우측 45도 없음</div><div class="slot-body"><b>우측 45도 · 필수</b><div class="actions"><a id="right45Replace" class="secondary">교체</a><button class="secondary" disabled>삭제(보관처리)</button></div></div></div><div class="slot empty"><div id="frontPreview" class="preview no-image">정면이미지 없음</div><div class="slot-body"><b>정면 · 필수</b><a id="frontUpload" class="secondary">등록</a></div></div></div></div></section>
<section id="content" class="panel"><div class="card"><div class="top"><div><h2 style="margin:0">판매콘텐츠</h2><div class="muted">기존 상품 콘텐츠 제작입구를 완성 결과와 빈 슬롯 중심으로 바꿉니다.</div></div><a id="contentWorkspace" class="secondary">콘텐츠 작업 열기</a></div><div class="assets" style="margin-top:14px"><div class="slot"><div class="preview">상세페이지 미리보기</div><div class="slot-body"><b>상세페이지</b><div class="muted">별도 제작화면에서 수정</div><a id="detailPage" class="secondary">제작화면</a></div></div><div class="slot empty"><div class="preview">리플릿 없음</div><div class="slot-body"><button class="secondary" disabled>제작 기능 연결 예정</button></div></div><div class="slot empty"><div class="preview">B2B 상품 카드 없음</div><div class="slot-body"><button class="secondary" disabled>제작 기능 연결 예정</button></div></div></div></div></section>
<section id="channel" class="panel"><div class="card"><h2>판매채널</h2><p class="muted">내부 등록 준비정보만 저장합니다. 네이버·쿠팡·자사몰 실제 반영은 별도 검증·승인 후 실행합니다. 전체 등록항목과 엑셀 연동은 2단계입니다.</p><div id="channelRows"></div></div></section>
<section id="history" class="panel"><div class="card"><h2>변경·작업이력</h2><p class="muted">상품 생성·최근 수정 시각과 이번 화면의 실행 경계를 확인합니다.</p><div id="historyRows"></div></div></section>

<div class="footer"><div id="saveStatus" class="muted">변경사항 없음</div><div class="actions"><button class="secondary" onclick="location.reload()">변경 취소</button><button class="primary" onclick="saveAll()">변경사항 저장</button></div></div>
</div><div id="lightbox" class="lightbox" role="dialog" aria-modal="true" aria-label="이미지 확대보기" onclick="closeLightbox(event)"><button class="secondary" type="button" onclick="closeLightbox(event,true)">닫기 ×</button><img id="lightboxImage" alt="확대 이미지"></div><script>
const tenant='__legacy__',productId=decodeURIComponent(location.pathname.split('/').pop());let product=null,dirty=false;
const $=id=>document.getElementById(id),val=id=>$(id).value,clean=v=>v===''?null:v,num=v=>v===''?null:Number(v),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),lines=id=>val(id).split('\n').map(x=>x.trim()).filter(Boolean);
async function request(path,options={}){const r=await fetch(path,{credentials:'same-origin',...options}),d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:JSON.stringify(d.detail||r.status));return d}
function showTab(id){document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('on',x.id===id));document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('on',x.dataset.tab===id))}
function markDirty(){dirty=true;$('saveStatus').textContent='저장하지 않은 변경사항이 있습니다.'}
function openLightbox(url,alt){if(!url)return;$('lightboxImage').src=url;$('lightboxImage').alt=alt;$('lightbox').classList.add('on')}
function closeLightbox(event,force=false){if(force||event.target===$('lightbox')){$('lightbox').classList.remove('on');$('lightboxImage').removeAttribute('src')}}
function setPreview(id,image,label){const el=$(id);if(!image){el.className='preview no-image';el.textContent=label+' 없음';return}const url=image.fact_content_url||image.raw_content_url;el.className='preview';el.innerHTML=`<img src="${esc(url)}" alt="${esc(label)}">`;el.onclick=()=>openLightbox(url,label)}
async function loadAssetImages(){try{const data=await request(`/api/v1/product-image-facts/products/${product.id}?tenant_id=${tenant}`),confirmed=data.images.filter(x=>x.status==='confirmed');const right=confirmed.find(x=>x.slot_type==='RIGHT_45'),primary=confirmed.find(x=>x.is_primary)||right,front=confirmed.find(x=>x.slot_type==='FRONT');setPreview('primaryPreview',primary,'대표이미지');setPreview('right45Preview',right,'우측 45도');setPreview('frontPreview',front,'정면')}catch(e){$('primaryPreview').textContent='이미지를 불러오지 못했습니다';$('saveStatus').textContent='이미지 자료 확인 필요: '+e}}
function skuIdentity(s,i){const p=`s${i}_`;return `<div class="sku"><div class="grid three"><div><label>SKU 코드</label><input value="${esc(s.sku_code)}" disabled></div><div><label>SKU명 *</label><input id="${p}name" value="${esc(s.name)}"></div><div><label>옵션값</label><input id="${p}option" value="${esc(s.option_value||'')}"></div><div><label>바코드</label><input id="${p}barcode" value="${esc(s.barcode||'')}"></div><div><label>판매단위</label><select id="${p}unit"><option value="each" ${s.sales_unit==='each'?'selected':''}>낱개</option><option value="box" ${s.sales_unit==='box'?'selected':''}>박스</option><option value="set" ${s.sales_unit==='set'?'selected':''}>세트</option></select></div><div><label>상태</label><select id="${p}status"><option value="draft" ${s.status==='draft'?'selected':''}>초안</option><option value="active" ${s.status==='active'?'selected':''}>활성</option><option value="inactive" ${s.status==='inactive'?'selected':''}>비활성</option></select></div></div></div>`}
function skuCommercial(s,i){const p=`s${i}_`;return `<div class="sku"><b class="code">${esc(s.sku_code)}</b><div class="grid three" style="margin-top:12px"><div><label>매입원가</label><input type="number" min="0" id="${p}cost" value="${s.purchase_cost??''}"></div><div><label>정상 판매가</label><input type="number" min="0" id="${p}list" value="${s.list_price??''}"></div><div><label>현재 판매가</label><input type="number" min="0" id="${p}sale" value="${s.sale_price??''}"></div><div><label>현재고</label><input type="number" min="0" id="${p}current" value="${s.current_stock??0}"></div><div><label>가용재고</label><input type="number" min="0" id="${p}available" value="${s.available_stock??0}"></div><div><label>안전재고</label><input type="number" min="0" id="${p}safety" value="${s.safety_stock??0}"></div><div><label>입고 예정</label><input type="number" min="0" id="${p}incoming" value="${s.incoming_stock??0}"></div><div><label>보관 위치</label><input id="${p}location" value="${esc(s.storage_location||'')}"></div><div><label>배송조건</label><input value="별도 배송설정 연결 예정" disabled></div></div></div>`}
function channelRows(){return product.skus.map((s,i)=>`<div class="sku"><b>${esc(s.name)}</b> <span class="code">${esc(s.sku_code)}</span>${['naver','coupang','own_store'].map(c=>{const x=s.channels.find(v=>v.channel===c)||{},p=`c${i}_${c}_`;return `<div class="grid three" style="margin-top:12px"><div><label>${{naver:'네이버',coupang:'쿠팡',own_store:'자사몰'}[c]} 상태</label><select id="${p}status">${['unlinked','linked','pending','active','error','stopped'].map(v=>`<option value="${v}" ${(x.status||'unlinked')===v?'selected':''}>${v}</option>`).join('')}</select></div><div><label>채널 상품번호</label><input id="${p}product" value="${esc(x.external_product_id||'')}"></div><div><label>채널 SKU 번호</label><input id="${p}sku" value="${esc(x.external_sku_id||'')}"></div><div><label>채널 상품명</label><input id="${p}name" value="${esc(x.channel_product_name||'')}"></div><div><label>채널 판매가</label><input type="number" min="0" id="${p}price" value="${x.channel_price??''}"></div></div>`}).join('')}</div>`).join('')||'<p class="muted">SKU를 먼저 등록하세요.</p>'}
function bind(){const n=product.narrative||{};$('title').textContent=product.name;$('subtitle').innerHTML=`<span class="code">${esc(product.product_code)}</span> · 상품별 통합 관리`;$('name').value=product.name;$('productCode').value=product.product_code;$('category').value=product.category||'';$('productStatus').value=product.status;$('brand').value=product.brand||'';$('modelName').value=product.model_name||'';$('manufacturer').value=product.manufacturer||'';$('origin').value=product.country_of_origin||'';$('supplier').value=product.supplier_name||'';$('description').value=product.description||'';$('features').value=(n.features||[]).join('\n');$('advantages').value=(n.advantages||[]).join('\n');$('limitations').value=(n.limitations||[]).join('\n');$('recommendedUses').value=(n.recommended_uses||[]).join('\n');$('cautions').value=(n.cautions||[]).join('\n');$('skuIdentity').innerHTML=product.skus.map(skuIdentity).join('')||'<p class="muted">등록된 SKU가 없습니다.</p>';$('skuCommercial').innerHTML=product.skus.map(skuCommercial).join('')||'<p class="muted">등록된 SKU가 없습니다.</p>';$('channelRows').innerHTML=channelRows();$('historyRows').innerHTML=`<div class="grid"><div><label>상품 생성</label><div>${esc((product.created_at||'').replace('T',' ').slice(0,19))}</div></div><div><label>최근 수정</label><div>${esc((product.updated_at||'').replace('T',' ').slice(0,19))}</div></div><div><label>최근 실행 주체</label><div>대시보드 사용자</div></div><div><label>외부 실행</label><div class="warn">별도 승인 전 실행 안 함</div></div></div>`;['assetWorkspace','primaryReplace','right45Replace','frontUpload'].forEach(id=>$(id).href=`/image-assets?product_id=${product.id}`);$('factEvidence').href=`/product-registration?product_id=${product.id}`;$('contentWorkspace').href=`/products`;$('detailPage').href=`/detail-pages?product_id=${product.id}`;document.querySelectorAll('input:not([disabled]),select,textarea').forEach(x=>x.addEventListener('change',markDirty));dirty=false;$('saveStatus').textContent='변경사항 없음'}
function skuPayload(s,i){const p=`s${i}_`;return{id:s.id,name:val(p+'name'),option_value:clean(val(p+'option')),barcode:clean(val(p+'barcode')),sales_unit:val(p+'unit'),status:val(p+'status'),purchase_cost:num(val(p+'cost')),list_price:num(val(p+'list')),sale_price:num(val(p+'sale')),current_stock:Number(val(p+'current')||0),available_stock:Number(val(p+'available')||0),safety_stock:Number(val(p+'safety')||0),incoming_stock:Number(val(p+'incoming')||0),storage_location:clean(val(p+'location'))}}
function channelPayload(){return product.skus.flatMap((s,i)=>['naver','coupang','own_store'].map(c=>{const p=`c${i}_${c}_`;return{sku_id:s.id,channel:c,status:val(p+'status'),external_product_id:clean(val(p+'product')),external_sku_id:clean(val(p+'sku')),channel_product_name:clean(val(p+'name')),channel_price:num(val(p+'price'))}}))}
async function saveAll(){try{$('saveStatus').textContent='전체 변경사항 검사·저장 중…';const body={product:{name:val('name'),status:val('productStatus'),description:clean(val('description')),category:clean(val('category')),brand:clean(val('brand')),model_name:clean(val('modelName')),manufacturer:clean(val('manufacturer')),country_of_origin:clean(val('origin')),supplier_name:clean(val('supplier'))},narrative:{features:lines('features'),advantages:lines('advantages'),limitations:lines('limitations'),recommended_uses:lines('recommendedUses'),cautions:lines('cautions')},skus:product.skus.map(skuPayload),channels:channelPayload(),changed_by:'dashboard-user'};const result=await request(`/api/v1/commerce-catalog/products/${product.id}/detail?tenant_id=${tenant}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});$('saveStatus').innerHTML=`<span class="ok">내부 변경사항 저장 완료 · SKU ${result.saved.skus}개 · 채널 준비정보 ${result.saved.channels}개</span>${result.approval_required?' <span class="warn">외부 반영은 별도 승인 필요</span>':''}`;dirty=false;product=await request(`/api/v1/commerce-catalog/products/${productId}?tenant_id=${tenant}`)}catch(e){$('saveStatus').innerHTML=`<span class="bad">저장하지 않았습니다: ${esc(e)}</span>`}}
function showAiProposal(){$('aiProposal').style.display='block';$('saveStatus').textContent='AI 제안 생성 · 사용자 검토 대기'}function acceptProposal(){if(!val('limitations').includes('설치조건'))$('limitations').value+=(val('limitations')?'\n':'')+'성능은 수압과 설치조건에 따라 달라질 수 있음';markDirty();$('aiProposal').style.display='none'}function dismissProposal(){$('aiProposal').style.display='none'}function showSettings(){$('saveStatus').textContent='현재 설정: 원본 보존 · 제품 형태·규격 임의변경 금지 · 외부 실행 승인 필요'}async function readinessCheck(){try{$('saveStatus').textContent='등록 준비 점검 Agent 실행 중…';const result=await request(`/api/v1/commerce-catalog/products/${product.id}/readiness-review?tenant_id=${tenant}`);if(result.status==='PASS'){$('saveStatus').innerHTML='<span class="ok">등록 준비 점검 · PASS</span> · 외부 실행은 별도 승인 후 진행';return}$('saveStatus').innerHTML=`<span class="warn">등록 준비 점검 · REVIEW · 누락 ${result.missing_count}건</span>: ${result.missing_labels.map(esc).join(', ')} · 외부 실행 없음`}catch(e){$('saveStatus').innerHTML=`<span class="bad">등록 준비 점검 실패: ${esc(e)}</span>`}}
async function addSku(){const name=prompt('새 SKU 이름을 입력하세요.');if(!name)return;const body={name,option_value:clean(prompt('옵션값을 입력하세요.')||''),barcode:null,sales_unit:'each',status:'active',purchase_cost:null,list_price:null,sale_price:null,current_stock:0,available_stock:0,safety_stock:0,incoming_stock:0,storage_location:null};try{await request(`/api/v1/commerce-catalog/products/${product.id}/skus?tenant_id=${tenant}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});product=await request(`/api/v1/commerce-catalog/products/${productId}?tenant_id=${tenant}`);bind();showTab('sku')}catch(e){alert('SKU를 추가하지 못했습니다: '+e)}}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});async function init(){try{product=await request(`/api/v1/commerce-catalog/products/${productId}?tenant_id=${tenant}`);bind();await loadAssetImages()}catch(e){$('subtitle').textContent='상품을 불러오지 못했습니다: '+e}}init();
</script></body></html>'''
