"""DEC-096 approved single-page product registration."""

HTML = r'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>신규 상품 등록</title><style>
*{box-sizing:border-box}body{margin:0;background:#0b0f17;color:#e5e7eb;font-family:Inter,Pretendard,system-ui,sans-serif}.wrap{max-width:1080px;margin:auto;padding:28px}.top,.row,.actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.top{justify-content:space-between}.card{background:#111827;border:1px solid #263247;border-radius:14px;padding:20px;margin:15px 0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}label{display:block;color:#aab7ca;font-size:13px;margin-bottom:6px}input,textarea,select{width:100%;background:#0b1220;color:#fff;border:1px solid #35445a;border-radius:9px;padding:11px}textarea{min-height:82px}.modes{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.mode{border:1px solid #35445a;border-radius:11px;padding:14px;cursor:pointer}.mode.on{border-color:#60a5fa;background:#17233a}.muted{color:#8ea0b7}.pill{display:inline-block;background:#22304a;border-radius:999px;padding:5px 9px;margin:4px}.drop{border:1px dashed #4b5d78;border-radius:12px;padding:25px;text-align:center}.primary,.secondary{border:0;border-radius:9px;padding:11px 15px;cursor:pointer}.primary{background:#2563eb;color:#fff}.secondary{background:#233149;color:#fff}.footer{display:flex;justify-content:flex-end;margin-top:18px}.ok{color:#a7f3d0}.bad{color:#fca5a5}@media(max-width:700px){.wrap{padding:15px}.grid,.modes{grid-template-columns:1fr}}
</style></head><body><div class="wrap"><div class="top"><div><a href="/commerce-catalog" style="color:#bfdbfe;text-decoration:none">← 상품관리 센터</a><h1>신규 상품 등록</h1><p class="muted">기본값과 준비된 원본만 등록하고, 나머지는 통합상품관리에서 완성합니다.</p></div></div>
<div class="card"><h2>1. 기본정보</h2><div class="grid"><div><label>상품명 *</label><input id="name" placeholder="예: 관수 호스 세트"></div><div><label>상품 분류 *</label><input id="category" placeholder="예: 원예용품 > 관수용품"></div></div><div style="margin-top:14px"><label>간단한 설명·내부 메모</label><textarea id="description" placeholder="상품을 식별할 수 있는 기본 내용만 입력하세요."></textarea></div><p class="muted">상품코드는 생성 시 자동 발급됩니다.</p></div>
<div class="card"><h2>2. SKU 초기 구성</h2><div class="modes"><div class="mode on" data-mode="single" onclick="chooseMode('single')"><b>옵션 없는 단일상품</b><p class="muted">기본 SKU 1개 생성</p></div><div class="mode" data-mode="options" onclick="chooseMode('options')"><b>옵션이 있는 상품</b><p class="muted">입력값별 SKU 생성</p></div><div class="mode" data-mode="undecided" onclick="chooseMode('undecided')"><b>아직 결정하지 않음</b><p class="muted">상품만 우선 생성</p></div></div><div id="optionBox" style="display:none;margin-top:16px"><label>옵션값 (쉼표 또는 줄바꿈으로 구분)</label><textarea id="options" placeholder="10m, 20m, 30m" oninput="previewOptions()"></textarea><div id="optionType" class="muted"></div><div id="preview"></div></div></div>
<div class="card"><h2>3. 준비된 원본 자료</h2><div class="drop"><b>원본 이미지와 참고문서를 선택하세요</b><p class="muted">이미지는 여러 장을 한꺼번에 올립니다. 대표·45도·정면 지정은 통합상품관리의 등록 자료에서 합니다.</p><div class="actions" style="justify-content:center"><label class="secondary" style="margin:0;cursor:pointer">원본 이미지 선택<input id="images" type="file" accept="image/*" multiple hidden onchange="filesChanged()"></label><label class="secondary" style="margin:0;cursor:pointer">참고문서 선택<input id="documents" type="file" multiple hidden onchange="filesChanged()"></label></div><div id="files" class="muted"></div></div><p class="muted">자료가 없으면 건너뛸 수 있습니다.</p></div>
<div id="status" class="muted"></div><div class="footer"><button class="primary" onclick="createProduct()">상품 생성 후 통합관리로 이동</button></div></div><script>
const tenant='__legacy__';let workspaceId=null,mode='single';const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(path,options={}){const r=await fetch(path,{credentials:'same-origin',...options}),d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:JSON.stringify(d.detail||r.status));return d}
function chooseMode(v){mode=v;document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('on',x.dataset.mode===v));$('optionBox').style.display=v==='options'?'block':'none';previewOptions()}
function parsedOptions(){return mode==='options'?$('options').value.split(/[,\n]/).map(x=>x.trim()).filter(Boolean):[]}
function detect(values){if(!values.length)return'';const types=values.map(v=>/^[\d.]+\s*(ml|l|㎖|ℓ)$/i.test(v)?'용량':/^[\d.]+\s*(kg|g)$/i.test(v)?'중량':/^[\d.]+\s*(mm|cm|m)$/i.test(v)?'길이':/^[\d.]+\s*(개|입|pcs?)$/i.test(v)?'수량':'옵션');return types.every(x=>x===types[0])?types[0]:'옵션'}
function previewOptions(){const values=parsedOptions(),type=detect(values);$('optionType').textContent=values.length?`자동 인식: ${type} 기준 · 입력한 표기는 그대로 초기값으로 사용됩니다.`:'';$('preview').innerHTML=values.map(v=>`<span class="pill">${esc(v)}</span>`).join('')}
let selectedImages=[],selectedDocuments=[];
function fileKey(file){return `${file.name}:${file.size}:${file.lastModified}`}
function addUnique(target,files){const keys=new Set(target.map(fileKey));for(const file of files){if(!keys.has(fileKey(file))){target.push(file);keys.add(fileKey(file))}}}
function removeSelected(kind,index){(kind==='image'?selectedImages:selectedDocuments).splice(index,1);renderSelectedFiles()}
function renderSelectedFiles(){const rows=[...selectedImages.map((f,i)=>`<div>이미지 · ${esc(f.name)} <button type="button" onclick="removeSelected('image',${i})">삭제</button></div>`),...selectedDocuments.map((f,i)=>`<div>문서 · ${esc(f.name)} <button type="button" onclick="removeSelected('document',${i})">삭제</button></div>`)];$('files').innerHTML=rows.length?`${rows.length}개 선택${rows.join('')}`:'선택된 파일 없음'}
function filesChanged(){addUnique(selectedImages,[...$('images').files]);addUnique(selectedDocuments,[...$('documents').files]);$('images').value='';$('documents').value='';renderSelectedFiles()}
async function uploadImages(id){for(let i=0;i<selectedImages.length;i++){const form=new FormData();form.append('role',i===0?'primary':'additional');form.append('source_classification','unknown');form.append('file',selectedImages[i]);await api(`/api/v1/product-registration/products/${id}/images/upload?tenant_id=${tenant}`,{method:'POST',body:form})}}
async function uploadDocs(id){for(const file of selectedDocuments){const form=new FormData();form.append('source_kind','other');form.append('file',file);await api(`/api/v1/product-registration/products/${id}/sources/upload?tenant_id=${tenant}`,{method:'POST',body:form})}}
async function createProduct(){try{if(!$('name').value.trim()||!$('category').value.trim())throw Error('상품명과 상품 분류를 입력하세요.');$('status').textContent='상품과 원본 자료를 등록하는 중…';const data=await api(`/api/v1/product-registration/products?tenant_id=${tenant}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspace_id:workspaceId,name:$('name').value.trim(),category:$('category').value.trim(),description:$('description').value.trim()||null,options:parsedOptions()})});await uploadImages(data.product.id);await uploadDocs(data.product.id);$('status').innerHTML='<span class="ok">등록 완료 · 통합상품관리로 이동합니다.</span>';location.href=`/commerce-catalog/product/${data.product.id}`}catch(e){$('status').innerHTML=`<span class="bad">${esc(e.message||e)}</span>`}}
async function init(){try{const rows=await api(`/api/v1/business/workspaces?tenant_id=${tenant}`),w=rows.find(x=>x.slug==='commerce-ai')||rows[0];if(!w)throw Error('Workspace가 없습니다.');workspaceId=w.id}catch(e){$('status').textContent='로그인 후 다시 열어주세요. '+e}}init();
</script></body></html>'''
